ASN_MODULE_SOURCES=	\
	S1AP-PDU.c	\
	InitiatingMessage.c	\
	SuccessfulOutcome.c	\
	UnsuccessfulOutcome.c	\
	E-RAB-IE-ContainerList.c	\
	E-RAB-IE-ContainerPairList.c	\
	ProtocolError-IE-ContainerList.c	\
	HandoverRequired.c	\
	HandoverCommand.c	\
	E-RABSubjecttoDataForwardingList.c	\
	E-RABDataForwardingItem.c	\
	HandoverPreparationFailure.c	\
	HandoverRequest.c	\
	E-RABToBeSetupListHOReq.c	\
	E-RABToBeSetupItemHOReq.c	\
	HandoverRequestAcknowledge.c	\
	E-RABAdmittedList.c	\
	E-RABAdmittedItem.c	\
	E-RABFailedtoSetupListHOReqAck.c	\
	E-RABFailedToSetupItemHOReqAck.c	\
	HandoverFailure.c	\
	HandoverNotify.c	\
	PathSwitchRequest.c	\
	E-RABToBeSwitchedDLList.c	\
	E-RABToBeSwitchedDLItem.c	\
	PathSwitchRequestAcknowledge.c	\
	E-RABToBeSwitchedULList.c	\
	E-RABToBeSwitchedULItem.c	\
	PathSwitchRequestFailure.c	\
	HandoverCancel.c	\
	HandoverCancelAcknowledge.c	\
	E-RABSetupRequest.c	\
	E-RABToBeSetupListBearerSUReq.c	\
	E-RABToBeSetupItemBearerSUReq.c	\
	E-RABSetupResponse.c	\
	E-RABSetupListBearerSURes.c	\
	E-RABSetupItemBearerSURes.c	\
	E-RABModifyRequest.c	\
	E-RABToBeModifiedListBearerModReq.c	\
	E-RABToBeModifiedItemBearerModReq.c	\
	E-RABModifyResponse.c	\
	E-RABModifyListBearerModRes.c	\
	E-RABModifyItemBearerModRes.c	\
	E-RABReleaseCommand.c	\
	E-RABReleaseResponse.c	\
	E-RABReleaseListBearerRelComp.c	\
	E-RABReleaseItemBearerRelComp.c	\
	E-RABReleaseIndication.c	\
	InitialContextSetupRequest.c	\
	E-RABToBeSetupListCtxtSUReq.c	\
	E-RABToBeSetupItemCtxtSUReq.c	\
	InitialContextSetupResponse.c	\
	E-RABSetupListCtxtSURes.c	\
	E-RABSetupItemCtxtSURes.c	\
	InitialContextSetupFailure.c	\
	Paging.c	\
	TAIList.c	\
	TAIItem.c	\
	UEContextReleaseRequest.c	\
	UEContextReleaseCommand.c	\
	UEContextReleaseComplete.c	\
	UEContextModificationRequest.c	\
	UEContextModificationResponse.c	\
	UEContextModificationFailure.c	\
	UERadioCapabilityMatchRequest.c	\
	UERadioCapabilityMatchResponse.c	\
	DownlinkNASTransport.c	\
	InitialUEMessage.c	\
	UplinkNASTransport.c	\
	NASNonDeliveryIndication.c	\
	RerouteNASRequest.c	\
	S1-Message.c	\
	NASDeliveryIndication.c	\
	Reset.c	\
	ResetType.c	\
	ResetAll.c	\
	UE-associatedLogicalS1-ConnectionListRes.c	\
	ResetAcknowledge.c	\
	UE-associatedLogicalS1-ConnectionListResAck.c	\
	ErrorIndication.c	\
	S1SetupRequest.c	\
	S1SetupResponse.c	\
	S1SetupFailure.c	\
	ENBConfigurationUpdate.c	\
	ENBConfigurationUpdateAcknowledge.c	\
	ENBConfigurationUpdateFailure.c	\
	MMEConfigurationUpdate.c	\
	MMEConfigurationUpdateAcknowledge.c	\
	MMEConfigurationUpdateFailure.c	\
	DownlinkS1cdma2000tunnelling.c	\
	UplinkS1cdma2000tunnelling.c	\
	UECapabilityInfoIndication.c	\
	ENBStatusTransfer.c	\
	MMEStatusTransfer.c	\
	TraceStart.c	\
	TraceFailureIndication.c	\
	DeactivateTrace.c	\
	CellTrafficTrace.c	\
	LocationReportingControl.c	\
	LocationReportingFailureIndication.c	\
	LocationReport.c	\
	OverloadStart.c	\
	OverloadStop.c	\
	WriteReplaceWarningRequest.c	\
	WriteReplaceWarningResponse.c	\
	ENBDirectInformationTransfer.c	\
	Inter-SystemInformationTransferType.c	\
	MMEDirectInformationTransfer.c	\
	ENBConfigurationTransfer.c	\
	MMEConfigurationTransfer.c	\
	PrivateMessage.c	\
	KillRequest.c	\
	KillResponse.c	\
	PWSRestartIndication.c	\
	PWSFailureIndication.c	\
	DownlinkUEAssociatedLPPaTransport.c	\
	UplinkUEAssociatedLPPaTransport.c	\
	DownlinkNonUEAssociatedLPPaTransport.c	\
	UplinkNonUEAssociatedLPPaTransport.c	\
	E-RABModificationIndication.c	\
	E-RABToBeModifiedListBearerModInd.c	\
	E-RABToBeModifiedItemBearerModInd.c	\
	E-RABNotToBeModifiedListBearerModInd.c	\
	E-RABNotToBeModifiedItemBearerModInd.c	\
	CSGMembershipInfo.c	\
	E-RABModificationConfirm.c	\
	E-RABModifyListBearerModConf.c	\
	E-RABModifyItemBearerModConf.c	\
	UEContextModificationIndication.c	\
	UEContextModificationConfirm.c	\
	UEContextSuspendRequest.c	\
	UEContextSuspendResponse.c	\
	UEContextResumeRequest.c	\
	E-RABFailedToResumeListResumeReq.c	\
	E-RABFailedToResumeItemResumeReq.c	\
	UEContextResumeResponse.c	\
	E-RABFailedToResumeListResumeRes.c	\
	E-RABFailedToResumeItemResumeRes.c	\
	UEContextResumeFailure.c	\
	ConnectionEstablishmentIndication.c	\
	RetrieveUEInformation.c	\
	UEInformationTransfer.c	\
	Additional-GUTI.c	\
	AreaScopeOfMDT.c	\
	AllocationAndRetentionPriority.c	\
	AssistanceDataForCECapableUEs.c	\
	AssistanceDataForPaging.c	\
	AssistanceDataForRecommendedCells.c	\
	Bearers-SubjectToStatusTransferList.c	\
	Bearers-SubjectToStatusTransfer-Item.c	\
	BearerType.c	\
	BitRate.c	\
	BPLMNs.c	\
	BroadcastCancelledAreaList.c	\
	BroadcastCompletedAreaList.c	\
	CancelledCellinEAI.c	\
	CancelledCellinEAI-Item.c	\
	CancelledCellinTAI.c	\
	CancelledCellinTAI-Item.c	\
	Cause.c	\
	CauseMisc.c	\
	CauseProtocol.c	\
	CauseRadioNetwork.c	\
	CauseTransport.c	\
	CauseNas.c	\
	CellAccessMode.c	\
	CellIdentifierAndCELevelForCECapableUEs.c	\
	CELevel.c	\
	CE-mode-B-SupportIndicator.c	\
	CellIdentity.c	\
	CellID-Broadcast.c	\
	CellID-Broadcast-Item.c	\
	CellID-Cancelled.c	\
	CellID-Cancelled-Item.c	\
	CellBasedMDT.c	\
	CellIdListforMDT.c	\
	Cdma2000PDU.c	\
	Cdma2000RATType.c	\
	Cdma2000SectorID.c	\
	Cdma2000HOStatus.c	\
	Cdma2000HORequiredIndication.c	\
	Cdma2000OneXSRVCCInfo.c	\
	Cdma2000OneXMEID.c	\
	Cdma2000OneXMSI.c	\
	Cdma2000OneXPilot.c	\
	Cdma2000OneXRAND.c	\
	Cell-Size.c	\
	CellType.c	\
	CGI.c	\
	CI.c	\
	CNDomain.c	\
	ConcurrentWarningMessageIndicator.c	\
	Correlation-ID.c	\
	CSFallbackIndicator.c	\
	AdditionalCSFallbackIndicator.c	\
	CSG-Id.c	\
	CSG-IdList.c	\
	CSG-IdList-Item.c	\
	CSGMembershipStatus.c	\
	COUNTvalue.c	\
	COUNTValueExtended.c	\
	COUNTvaluePDCP-SNlength18.c	\
	Coverage-Level.c	\
	CriticalityDiagnostics.c	\
	CriticalityDiagnostics-IE-List.c	\
	CriticalityDiagnostics-IE-Item.c	\
	DataCodingScheme.c	\
	DCN-ID.c	\
	ServedDCNs.c	\
	ServedDCNsItem.c	\
	DL-Forwarding.c	\
	Direct-Forwarding-Path-Availability.c	\
	Data-Forwarding-Not-Possible.c	\
	DLNASPDUDeliveryAckRequest.c	\
	EARFCN.c	\
	ECGIList.c	\
	PWSfailedECGIList.c	\
	EmergencyAreaIDList.c	\
	EmergencyAreaID.c	\
	EmergencyAreaID-Broadcast.c	\
	EmergencyAreaID-Broadcast-Item.c	\
	EmergencyAreaID-Cancelled.c	\
	EmergencyAreaID-Cancelled-Item.c	\
	CompletedCellinEAI.c	\
	CompletedCellinEAI-Item.c	\
	ECGI-List.c	\
	EmergencyAreaIDListForRestart.c	\
	ENB-ID.c	\
	GERAN-Cell-ID.c	\
	Global-ENB-ID.c	\
	GUMMEIList.c	\
	ENB-StatusTransfer-TransparentContainer.c	\
	ENB-UE-S1AP-ID.c	\
	ENBname.c	\
	ENBX2TLAs.c	\
	EncryptionAlgorithms.c	\
	EnhancedCoverageRestricted.c	\
	EPLMNs.c	\
	EventType.c	\
	E-RAB-ID.c	\
	E-RABInformationList.c	\
	E-RABInformationListItem.c	\
	E-RABList.c	\
	E-RABItem.c	\
	E-RABLevelQoSParameters.c	\
	EUTRAN-CGI.c	\
	EUTRANRoundTripDelayEstimationInfo.c	\
	ExpectedUEBehaviour.c	\
	ExpectedUEActivityBehaviour.c	\
	ExpectedActivityPeriod.c	\
	ExpectedIdlePeriod.c	\
	SourceOfUEActivityBehaviourInformation.c	\
	ExpectedHOInterval.c	\
	ExtendedRNC-ID.c	\
	ExtendedRepetitionPeriod.c	\
	Extended-UEIdentityIndexValue.c	\
	ForbiddenInterRATs.c	\
	ForbiddenTAs.c	\
	ForbiddenTAs-Item.c	\
	ForbiddenTACs.c	\
	ForbiddenLAs.c	\
	ForbiddenLAs-Item.c	\
	ForbiddenLACs.c	\
	GBR-QosInformation.c	\
	GTP-TEID.c	\
	GUMMEI.c	\
	GUMMEIType.c	\
	GWContextReleaseIndication.c	\
	HandoverRestrictionList.c	\
	HandoverType.c	\
	HFN.c	\
	HFNModified.c	\
	HFNforPDCP-SNlength18.c	\
	Masked-IMEISV.c	\
	ImmediateMDT.c	\
	IMSI.c	\
	InformationOnRecommendedCellsAndENBsForPaging.c	\
	IntegrityProtectionAlgorithms.c	\
	IntendedNumberOfPagingAttempts.c	\
	InterfacesToTrace.c	\
	KillAllWarningMessages.c	\
	LAC.c	\
	LAI.c	\
	LastVisitedCell-Item.c	\
	LastVisitedEUTRANCellInformation.c	\
	LastVisitedUTRANCellInformation.c	\
	LastVisitedGERANCellInformation.c	\
	L3-Information.c	\
	LPPa-PDU.c	\
	LHN-ID.c	\
	Links-to-log.c	\
	ListeningSubframePattern.c	\
	LoggedMDT.c	\
	LoggingInterval.c	\
	LoggingDuration.c	\
	LoggedMBSFNMDT.c	\
	M3Configuration.c	\
	M3period.c	\
	M4Configuration.c	\
	M4period.c	\
	M5Configuration.c	\
	M5period.c	\
	M6Configuration.c	\
	M6report-Interval.c	\
	M6delay-threshold.c	\
	M7Configuration.c	\
	M7period.c	\
	MDT-Activation.c	\
	MDT-Location-Info.c	\
	MDT-Configuration.c	\
	ManagementBasedMDTAllowed.c	\
	MBSFN-ResultToLog.c	\
	MBSFN-ResultToLogInfo.c	\
	MDTPLMNList.c	\
	PrivacyIndicator.c	\
	MDTMode.c	\
	MDTMode-Extension.c	\
	MeasurementsToActivate.c	\
	MeasurementThresholdA2.c	\
	MessageIdentifier.c	\
	S1AP-IEs_MobilityInformation.c	\
	MMEname.c	\
	MMEPagingTarget.c	\
	MMERelaySupportIndicator.c	\
	MME-Group-ID.c	\
	MME-Code.c	\
	MME-UE-S1AP-ID.c	\
	M-TMSI.c	\
	MSClassmark2.c	\
	MSClassmark3.c	\
	MutingAvailabilityIndication.c	\
	MutingPatternInformation.c	\
	NAS-PDU.c	\
	NASSecurityParametersfromE-UTRAN.c	\
	NASSecurityParameterstoE-UTRAN.c	\
	NB-IoT-DefaultPagingDRX.c	\
	NB-IoT-Paging-eDRXInformation.c	\
	NB-IoT-Paging-eDRX-Cycle.c	\
	NB-IoT-PagingTimeWindow.c	\
	NB-IoT-UEIdentityIndexValue.c	\
	NextPagingAreaScope.c	\
	NumberofBroadcastRequest.c	\
	NumberOfBroadcasts.c	\
	OldBSS-ToNewBSS-Information.c	\
	OverloadAction.c	\
	OverloadResponse.c	\
	PagingAttemptInformation.c	\
	PagingAttemptCount.c	\
	Paging-eDRXInformation.c	\
	Paging-eDRX-Cycle.c	\
	PagingTimeWindow.c	\
	PagingDRX.c	\
	PagingPriority.c	\
	PDCP-SN.c	\
	PDCP-SNExtended.c	\
	PDCP-SNlength18.c	\
	M1PeriodicReporting.c	\
	PLMNidentity.c	\
	Port-Number.c	\
	Pre-emptionCapability.c	\
	Pre-emptionVulnerability.c	\
	PriorityLevel.c	\
	ProSeAuthorized.c	\
	ProSeDirectDiscovery.c	\
	ProSeUEtoNetworkRelaying.c	\
	ProSeDirectCommunication.c	\
	PS-ServiceNotAvailable.c	\
	QCI.c	\
	ReceiveStatusofULPDCPSDUs.c	\
	ReceiveStatusOfULPDCPSDUsExtended.c	\
	ReceiveStatusOfULPDCPSDUsPDCP-SNlength18.c	\
	RecommendedCellsForPaging.c	\
	RecommendedCellList.c	\
	RecommendedCellItem.c	\
	RecommendedENBsForPaging.c	\
	RecommendedENBList.c	\
	RecommendedENBItem.c	\
	RelativeMMECapacity.c	\
	RelayNode-Indicator.c	\
	RAC.c	\
	RAT-Type.c	\
	ReportAmountMDT.c	\
	ReportIntervalMDT.c	\
	M1ReportingTrigger.c	\
	RequestType.c	\
	RIMTransfer.c	\
	RIMInformation.c	\
	RIMRoutingAddress.c	\
	ReportArea.c	\
	RepetitionPeriod.c	\
	RLFReportInformation.c	\
	RNC-ID.c	\
	RRC-Container.c	\
	RRC-Establishment-Cause.c	\
	ECGIListForRestart.c	\
	Routing-ID.c	\
	SecurityKey.c	\
	SecurityContext.c	\
	SerialNumber.c	\
	SONInformation.c	\
	SONInformation-Extension.c	\
	SONInformationRequest.c	\
	SONInformationReply.c	\
	SONInformationReport.c	\
	SONConfigurationTransfer.c	\
	SynchronisationInformation.c	\
	Source-ToTarget-TransparentContainer.c	\
	SourceBSS-ToTargetBSS-TransparentContainer.c	\
	SourceeNB-ID.c	\
	SRVCCOperationNotPossible.c	\
	SRVCCOperationPossible.c	\
	SRVCCHOIndication.c	\
	SourceeNB-ToTargeteNB-TransparentContainer.c	\
	SourceRNC-ToTargetRNC-TransparentContainer.c	\
	ServedGUMMEIs.c	\
	ServedGUMMEIsItem.c	\
	ServedGroupIDs.c	\
	ServedMMECs.c	\
	ServedPLMNs.c	\
	SubscriberProfileIDforRFP.c	\
	SupportedTAs.c	\
	SupportedTAs-Item.c	\
	StratumLevel.c	\
	SynchronisationStatus.c	\
	TimeSynchronisationInfo.c	\
	S-TMSI.c	\
	TAC.c	\
	TAIBasedMDT.c	\
	TAIListforMDT.c	\
	TAIListforWarning.c	\
	TAI.c	\
	TAI-Broadcast.c	\
	TAI-Broadcast-Item.c	\
	TAI-Cancelled.c	\
	TAI-Cancelled-Item.c	\
	TABasedMDT.c	\
	TAListforMDT.c	\
	CompletedCellinTAI.c	\
	CompletedCellinTAI-Item.c	\
	TBCD-STRING.c	\
	TargetID.c	\
	TargeteNB-ID.c	\
	TargetRNC-ID.c	\
	TargeteNB-ToSourceeNB-TransparentContainer.c	\
	Target-ToSource-TransparentContainer.c	\
	TargetRNC-ToSourceRNC-TransparentContainer.c	\
	TargetBSS-ToSourceBSS-TransparentContainer.c	\
	M1ThresholdEventA2.c	\
	Threshold-RSRP.c	\
	Threshold-RSRQ.c	\
	TimeToWait.c	\
	Time-UE-StayedInCell.c	\
	Time-UE-StayedInCell-EnhancedGranularity.c	\
	TransportInformation.c	\
	TransportLayerAddress.c	\
	TraceActivation.c	\
	TraceDepth.c	\
	E-UTRAN-Trace-ID.c	\
	TrafficLoadReductionIndication.c	\
	TunnelInformation.c	\
	TypeOfError.c	\
	TAIListForRestart.c	\
	UEAggregateMaximumBitrate.c	\
	UE-RetentionInformation.c	\
	UE-S1AP-IDs.c	\
	UE-S1AP-ID-pair.c	\
	UE-associatedLogicalS1-ConnectionItem.c	\
	UEIdentityIndexValue.c	\
	UE-HistoryInformation.c	\
	UE-HistoryInformationFromTheUE.c	\
	UEPagingID.c	\
	UERadioCapability.c	\
	UERadioCapabilityForPaging.c	\
	UE-RLF-Report-Container.c	\
	UE-RLF-Report-Container-for-extended-bands.c	\
	UESecurityCapabilities.c	\
	UESidelinkAggregateMaximumBitrate.c	\
	UE-Usage-Type.c	\
	UserLocationInformation.c	\
	UEUserPlaneCIoTSupportIndicator.c	\
	VoiceSupportMatchIndicator.c	\
	V2XServicesAuthorized.c	\
	VehicleUE.c	\
	PedestrianUE.c	\
	WarningAreaList.c	\
	WarningType.c	\
	WarningSecurityInfo.c	\
	WarningMessageContents.c	\
	X2TNLConfigurationInfo.c	\
	ENBX2ExtTLAs.c	\
	ENBX2ExtTLA.c	\
	ENBX2GTPTLAs.c	\
	ENBIndirectX2TransportLayerAddresses.c	\
	Criticality.c	\
	Presence.c	\
	PrivateIE-ID.c	\
	ProcedureCode.c	\
	ProtocolExtensionID.c	\
	ProtocolIE-ID.c	\
	TriggeringMessage.c	\
	ProtocolIE-Container.c	\
	ProtocolIE-SingleContainer.c	\
	ProtocolIE-Field.c	\
	ProtocolIE-ContainerPair.c	\
	ProtocolIE-FieldPair.c	\
	ProtocolIE-ContainerList.c	\
	ProtocolIE-ContainerPairList.c	\
	ProtocolExtensionContainer.c	\
	ProtocolExtensionField.c	\
	PrivateIE-Container.c	\
	PrivateIE-Field.c	\
	SONtransferApplicationIdentity.c	\
	SONtransferRequestContainer.c	\
	SONtransferResponseContainer.c	\
	SONtransferCause.c	\
	CellLoadReportingCause.c	\
	HOReportingCause.c	\
	CellActivationCause.c	\
	CellStateIndicationCause.c	\
	FailureEventReportingCause.c	\
	CellLoadReportingResponse.c	\
	CompositeAvailableCapacityGroup.c	\
	EUTRANcellLoadReportingResponse.c	\
	EUTRANResponse.c	\
	EHRPD-Sector-ID.c	\
	IRAT-Cell-ID.c	\
	RequestedCellList.c	\
	MultiCellLoadReportingRequest.c	\
	ReportingCellList-Item.c	\
	ReportingCellList.c	\
	MultiCellLoadReportingResponse.c	\
	MultiCellLoadReportingResponse-Item.c	\
	NumberOfMeasurementReportingLevels.c	\
	EventTriggeredCellLoadReportingRequest.c	\
	OverloadFlag.c	\
	EventTriggeredCellLoadReportingResponse.c	\
	HOReport.c	\
	HoType.c	\
	HoReportType.c	\
	CandidateCellList.c	\
	CandidatePCIList.c	\
	CandidatePCI.c	\
	CellActivationRequest.c	\
	CellsToActivateList.c	\
	CellsToActivateList-Item.c	\
	CellActivationResponse.c	\
	ActivatedCellsList.c	\
	ActivatedCellsList-Item.c	\
	CellStateIndication.c	\
	NotificationCellList.c	\
	NotificationCellList-Item.c	\
	NotifyFlag.c	\
	FailureEventReport.c	\
	TooEarlyInterRATHOReportReportFromEUTRAN.c	\
	SonTransfer-IEs_MobilityInformation.c	\
	EHRPDCapacityValue.c	\
	EHRPDSectorCapacityClassValue.c	\
	EHRPDSectorLoadReportingResponse.c	\
	EHRPDCompositeAvailableCapacity.c	\
	EHRPDMultiSectorLoadReportingResponseItem.c	\
	EXTERNAL.c

ASN_MODULE_HEADERS=	\
	S1AP-PDU.h	\
	InitiatingMessage.h	\
	SuccessfulOutcome.h	\
	UnsuccessfulOutcome.h	\
	E-RAB-IE-ContainerList.h	\
	E-RAB-IE-ContainerPairList.h	\
	ProtocolError-IE-ContainerList.h	\
	HandoverRequired.h	\
	HandoverCommand.h	\
	E-RABSubjecttoDataForwardingList.h	\
	E-RABDataForwardingItem.h	\
	HandoverPreparationFailure.h	\
	HandoverRequest.h	\
	E-RABToBeSetupListHOReq.h	\
	E-RABToBeSetupItemHOReq.h	\
	HandoverRequestAcknowledge.h	\
	E-RABAdmittedList.h	\
	E-RABAdmittedItem.h	\
	E-RABFailedtoSetupListHOReqAck.h	\
	E-RABFailedToSetupItemHOReqAck.h	\
	HandoverFailure.h	\
	HandoverNotify.h	\
	PathSwitchRequest.h	\
	E-RABToBeSwitchedDLList.h	\
	E-RABToBeSwitchedDLItem.h	\
	PathSwitchRequestAcknowledge.h	\
	E-RABToBeSwitchedULList.h	\
	E-RABToBeSwitchedULItem.h	\
	PathSwitchRequestFailure.h	\
	HandoverCancel.h	\
	HandoverCancelAcknowledge.h	\
	E-RABSetupRequest.h	\
	E-RABToBeSetupListBearerSUReq.h	\
	E-RABToBeSetupItemBearerSUReq.h	\
	E-RABSetupResponse.h	\
	E-RABSetupListBearerSURes.h	\
	E-RABSetupItemBearerSURes.h	\
	E-RABModifyRequest.h	\
	E-RABToBeModifiedListBearerModReq.h	\
	E-RABToBeModifiedItemBearerModReq.h	\
	E-RABModifyResponse.h	\
	E-RABModifyListBearerModRes.h	\
	E-RABModifyItemBearerModRes.h	\
	E-RABReleaseCommand.h	\
	E-RABReleaseResponse.h	\
	E-RABReleaseListBearerRelComp.h	\
	E-RABReleaseItemBearerRelComp.h	\
	E-RABReleaseIndication.h	\
	InitialContextSetupRequest.h	\
	E-RABToBeSetupListCtxtSUReq.h	\
	E-RABToBeSetupItemCtxtSUReq.h	\
	InitialContextSetupResponse.h	\
	E-RABSetupListCtxtSURes.h	\
	E-RABSetupItemCtxtSURes.h	\
	InitialContextSetupFailure.h	\
	Paging.h	\
	TAIList.h	\
	TAIItem.h	\
	UEContextReleaseRequest.h	\
	UEContextReleaseCommand.h	\
	UEContextReleaseComplete.h	\
	UEContextModificationRequest.h	\
	UEContextModificationResponse.h	\
	UEContextModificationFailure.h	\
	UERadioCapabilityMatchRequest.h	\
	UERadioCapabilityMatchResponse.h	\
	DownlinkNASTransport.h	\
	InitialUEMessage.h	\
	UplinkNASTransport.h	\
	NASNonDeliveryIndication.h	\
	RerouteNASRequest.h	\
	S1-Message.h	\
	NASDeliveryIndication.h	\
	Reset.h	\
	ResetType.h	\
	ResetAll.h	\
	UE-associatedLogicalS1-ConnectionListRes.h	\
	ResetAcknowledge.h	\
	UE-associatedLogicalS1-ConnectionListResAck.h	\
	ErrorIndication.h	\
	S1SetupRequest.h	\
	S1SetupResponse.h	\
	S1SetupFailure.h	\
	ENBConfigurationUpdate.h	\
	ENBConfigurationUpdateAcknowledge.h	\
	ENBConfigurationUpdateFailure.h	\
	MMEConfigurationUpdate.h	\
	MMEConfigurationUpdateAcknowledge.h	\
	MMEConfigurationUpdateFailure.h	\
	DownlinkS1cdma2000tunnelling.h	\
	UplinkS1cdma2000tunnelling.h	\
	UECapabilityInfoIndication.h	\
	ENBStatusTransfer.h	\
	MMEStatusTransfer.h	\
	TraceStart.h	\
	TraceFailureIndication.h	\
	DeactivateTrace.h	\
	CellTrafficTrace.h	\
	LocationReportingControl.h	\
	LocationReportingFailureIndication.h	\
	LocationReport.h	\
	OverloadStart.h	\
	OverloadStop.h	\
	WriteReplaceWarningRequest.h	\
	WriteReplaceWarningResponse.h	\
	ENBDirectInformationTransfer.h	\
	Inter-SystemInformationTransferType.h	\
	MMEDirectInformationTransfer.h	\
	ENBConfigurationTransfer.h	\
	MMEConfigurationTransfer.h	\
	PrivateMessage.h	\
	KillRequest.h	\
	KillResponse.h	\
	PWSRestartIndication.h	\
	PWSFailureIndication.h	\
	DownlinkUEAssociatedLPPaTransport.h	\
	UplinkUEAssociatedLPPaTransport.h	\
	DownlinkNonUEAssociatedLPPaTransport.h	\
	UplinkNonUEAssociatedLPPaTransport.h	\
	E-RABModificationIndication.h	\
	E-RABToBeModifiedListBearerModInd.h	\
	E-RABToBeModifiedItemBearerModInd.h	\
	E-RABNotToBeModifiedListBearerModInd.h	\
	E-RABNotToBeModifiedItemBearerModInd.h	\
	CSGMembershipInfo.h	\
	E-RABModificationConfirm.h	\
	E-RABModifyListBearerModConf.h	\
	E-RABModifyItemBearerModConf.h	\
	UEContextModificationIndication.h	\
	UEContextModificationConfirm.h	\
	UEContextSuspendRequest.h	\
	UEContextSuspendResponse.h	\
	UEContextResumeRequest.h	\
	E-RABFailedToResumeListResumeReq.h	\
	E-RABFailedToResumeItemResumeReq.h	\
	UEContextResumeResponse.h	\
	E-RABFailedToResumeListResumeRes.h	\
	E-RABFailedToResumeItemResumeRes.h	\
	UEContextResumeFailure.h	\
	ConnectionEstablishmentIndication.h	\
	RetrieveUEInformation.h	\
	UEInformationTransfer.h	\
	Additional-GUTI.h	\
	AreaScopeOfMDT.h	\
	AllocationAndRetentionPriority.h	\
	AssistanceDataForCECapableUEs.h	\
	AssistanceDataForPaging.h	\
	AssistanceDataForRecommendedCells.h	\
	Bearers-SubjectToStatusTransferList.h	\
	Bearers-SubjectToStatusTransfer-Item.h	\
	BearerType.h	\
	BitRate.h	\
	BPLMNs.h	\
	BroadcastCancelledAreaList.h	\
	BroadcastCompletedAreaList.h	\
	CancelledCellinEAI.h	\
	CancelledCellinEAI-Item.h	\
	CancelledCellinTAI.h	\
	CancelledCellinTAI-Item.h	\
	Cause.h	\
	CauseMisc.h	\
	CauseProtocol.h	\
	CauseRadioNetwork.h	\
	CauseTransport.h	\
	CauseNas.h	\
	CellAccessMode.h	\
	CellIdentifierAndCELevelForCECapableUEs.h	\
	CELevel.h	\
	CE-mode-B-SupportIndicator.h	\
	CellIdentity.h	\
	CellID-Broadcast.h	\
	CellID-Broadcast-Item.h	\
	CellID-Cancelled.h	\
	CellID-Cancelled-Item.h	\
	CellBasedMDT.h	\
	CellIdListforMDT.h	\
	Cdma2000PDU.h	\
	Cdma2000RATType.h	\
	Cdma2000SectorID.h	\
	Cdma2000HOStatus.h	\
	Cdma2000HORequiredIndication.h	\
	Cdma2000OneXSRVCCInfo.h	\
	Cdma2000OneXMEID.h	\
	Cdma2000OneXMSI.h	\
	Cdma2000OneXPilot.h	\
	Cdma2000OneXRAND.h	\
	Cell-Size.h	\
	CellType.h	\
	CGI.h	\
	CI.h	\
	CNDomain.h	\
	ConcurrentWarningMessageIndicator.h	\
	Correlation-ID.h	\
	CSFallbackIndicator.h	\
	AdditionalCSFallbackIndicator.h	\
	CSG-Id.h	\
	CSG-IdList.h	\
	CSG-IdList-Item.h	\
	CSGMembershipStatus.h	\
	COUNTvalue.h	\
	COUNTValueExtended.h	\
	COUNTvaluePDCP-SNlength18.h	\
	Coverage-Level.h	\
	CriticalityDiagnostics.h	\
	CriticalityDiagnostics-IE-List.h	\
	CriticalityDiagnostics-IE-Item.h	\
	DataCodingScheme.h	\
	DCN-ID.h	\
	ServedDCNs.h	\
	ServedDCNsItem.h	\
	DL-Forwarding.h	\
	Direct-Forwarding-Path-Availability.h	\
	Data-Forwarding-Not-Possible.h	\
	DLNASPDUDeliveryAckRequest.h	\
	EARFCN.h	\
	ECGIList.h	\
	PWSfailedECGIList.h	\
	EmergencyAreaIDList.h	\
	EmergencyAreaID.h	\
	EmergencyAreaID-Broadcast.h	\
	EmergencyAreaID-Broadcast-Item.h	\
	EmergencyAreaID-Cancelled.h	\
	EmergencyAreaID-Cancelled-Item.h	\
	CompletedCellinEAI.h	\
	CompletedCellinEAI-Item.h	\
	ECGI-List.h	\
	EmergencyAreaIDListForRestart.h	\
	ENB-ID.h	\
	GERAN-Cell-ID.h	\
	Global-ENB-ID.h	\
	GUMMEIList.h	\
	ENB-StatusTransfer-TransparentContainer.h	\
	ENB-UE-S1AP-ID.h	\
	ENBname.h	\
	ENBX2TLAs.h	\
	EncryptionAlgorithms.h	\
	EnhancedCoverageRestricted.h	\
	EPLMNs.h	\
	EventType.h	\
	E-RAB-ID.h	\
	E-RABInformationList.h	\
	E-RABInformationListItem.h	\
	E-RABList.h	\
	E-RABItem.h	\
	E-RABLevelQoSParameters.h	\
	EUTRAN-CGI.h	\
	EUTRANRoundTripDelayEstimationInfo.h	\
	ExpectedUEBehaviour.h	\
	ExpectedUEActivityBehaviour.h	\
	ExpectedActivityPeriod.h	\
	ExpectedIdlePeriod.h	\
	SourceOfUEActivityBehaviourInformation.h	\
	ExpectedHOInterval.h	\
	ExtendedRNC-ID.h	\
	ExtendedRepetitionPeriod.h	\
	Extended-UEIdentityIndexValue.h	\
	ForbiddenInterRATs.h	\
	ForbiddenTAs.h	\
	ForbiddenTAs-Item.h	\
	ForbiddenTACs.h	\
	ForbiddenLAs.h	\
	ForbiddenLAs-Item.h	\
	ForbiddenLACs.h	\
	GBR-QosInformation.h	\
	GTP-TEID.h	\
	GUMMEI.h	\
	GUMMEIType.h	\
	GWContextReleaseIndication.h	\
	HandoverRestrictionList.h	\
	HandoverType.h	\
	HFN.h	\
	HFNModified.h	\
	HFNforPDCP-SNlength18.h	\
	Masked-IMEISV.h	\
	ImmediateMDT.h	\
	IMSI.h	\
	InformationOnRecommendedCellsAndENBsForPaging.h	\
	IntegrityProtectionAlgorithms.h	\
	IntendedNumberOfPagingAttempts.h	\
	InterfacesToTrace.h	\
	KillAllWarningMessages.h	\
	LAC.h	\
	LAI.h	\
	LastVisitedCell-Item.h	\
	LastVisitedEUTRANCellInformation.h	\
	LastVisitedUTRANCellInformation.h	\
	LastVisitedGERANCellInformation.h	\
	L3-Information.h	\
	LPPa-PDU.h	\
	LHN-ID.h	\
	Links-to-log.h	\
	ListeningSubframePattern.h	\
	LoggedMDT.h	\
	LoggingInterval.h	\
	LoggingDuration.h	\
	LoggedMBSFNMDT.h	\
	M3Configuration.h	\
	M3period.h	\
	M4Configuration.h	\
	M4period.h	\
	M5Configuration.h	\
	M5period.h	\
	M6Configuration.h	\
	M6report-Interval.h	\
	M6delay-threshold.h	\
	M7Configuration.h	\
	M7period.h	\
	MDT-Activation.h	\
	MDT-Location-Info.h	\
	MDT-Configuration.h	\
	ManagementBasedMDTAllowed.h	\
	MBSFN-ResultToLog.h	\
	MBSFN-ResultToLogInfo.h	\
	MDTPLMNList.h	\
	PrivacyIndicator.h	\
	MDTMode.h	\
	MDTMode-Extension.h	\
	MeasurementsToActivate.h	\
	MeasurementThresholdA2.h	\
	MessageIdentifier.h	\
	S1AP-IEs_MobilityInformation.h	\
	MMEname.h	\
	MMEPagingTarget.h	\
	MMERelaySupportIndicator.h	\
	MME-Group-ID.h	\
	MME-Code.h	\
	MME-UE-S1AP-ID.h	\
	M-TMSI.h	\
	MSClassmark2.h	\
	MSClassmark3.h	\
	MutingAvailabilityIndication.h	\
	MutingPatternInformation.h	\
	NAS-PDU.h	\
	NASSecurityParametersfromE-UTRAN.h	\
	NASSecurityParameterstoE-UTRAN.h	\
	NB-IoT-DefaultPagingDRX.h	\
	NB-IoT-Paging-eDRXInformation.h	\
	NB-IoT-Paging-eDRX-Cycle.h	\
	NB-IoT-PagingTimeWindow.h	\
	NB-IoT-UEIdentityIndexValue.h	\
	NextPagingAreaScope.h	\
	NumberofBroadcastRequest.h	\
	NumberOfBroadcasts.h	\
	OldBSS-ToNewBSS-Information.h	\
	OverloadAction.h	\
	OverloadResponse.h	\
	PagingAttemptInformation.h	\
	PagingAttemptCount.h	\
	Paging-eDRXInformation.h	\
	Paging-eDRX-Cycle.h	\
	PagingTimeWindow.h	\
	PagingDRX.h	\
	PagingPriority.h	\
	PDCP-SN.h	\
	PDCP-SNExtended.h	\
	PDCP-SNlength18.h	\
	M1PeriodicReporting.h	\
	PLMNidentity.h	\
	Port-Number.h	\
	Pre-emptionCapability.h	\
	Pre-emptionVulnerability.h	\
	PriorityLevel.h	\
	ProSeAuthorized.h	\
	ProSeDirectDiscovery.h	\
	ProSeUEtoNetworkRelaying.h	\
	ProSeDirectCommunication.h	\
	PS-ServiceNotAvailable.h	\
	QCI.h	\
	ReceiveStatusofULPDCPSDUs.h	\
	ReceiveStatusOfULPDCPSDUsExtended.h	\
	ReceiveStatusOfULPDCPSDUsPDCP-SNlength18.h	\
	RecommendedCellsForPaging.h	\
	RecommendedCellList.h	\
	RecommendedCellItem.h	\
	RecommendedENBsForPaging.h	\
	RecommendedENBList.h	\
	RecommendedENBItem.h	\
	RelativeMMECapacity.h	\
	RelayNode-Indicator.h	\
	RAC.h	\
	RAT-Type.h	\
	ReportAmountMDT.h	\
	ReportIntervalMDT.h	\
	M1ReportingTrigger.h	\
	RequestType.h	\
	RIMTransfer.h	\
	RIMInformation.h	\
	RIMRoutingAddress.h	\
	ReportArea.h	\
	RepetitionPeriod.h	\
	RLFReportInformation.h	\
	RNC-ID.h	\
	RRC-Container.h	\
	RRC-Establishment-Cause.h	\
	ECGIListForRestart.h	\
	Routing-ID.h	\
	SecurityKey.h	\
	SecurityContext.h	\
	SerialNumber.h	\
	SONInformation.h	\
	SONInformation-Extension.h	\
	SONInformationRequest.h	\
	SONInformationReply.h	\
	SONInformationReport.h	\
	SONConfigurationTransfer.h	\
	SynchronisationInformation.h	\
	Source-ToTarget-TransparentContainer.h	\
	SourceBSS-ToTargetBSS-TransparentContainer.h	\
	SourceeNB-ID.h	\
	SRVCCOperationNotPossible.h	\
	SRVCCOperationPossible.h	\
	SRVCCHOIndication.h	\
	SourceeNB-ToTargeteNB-TransparentContainer.h	\
	SourceRNC-ToTargetRNC-TransparentContainer.h	\
	ServedGUMMEIs.h	\
	ServedGUMMEIsItem.h	\
	ServedGroupIDs.h	\
	ServedMMECs.h	\
	ServedPLMNs.h	\
	SubscriberProfileIDforRFP.h	\
	SupportedTAs.h	\
	SupportedTAs-Item.h	\
	StratumLevel.h	\
	SynchronisationStatus.h	\
	TimeSynchronisationInfo.h	\
	S-TMSI.h	\
	TAC.h	\
	TAIBasedMDT.h	\
	TAIListforMDT.h	\
	TAIListforWarning.h	\
	TAI.h	\
	TAI-Broadcast.h	\
	TAI-Broadcast-Item.h	\
	TAI-Cancelled.h	\
	TAI-Cancelled-Item.h	\
	TABasedMDT.h	\
	TAListforMDT.h	\
	CompletedCellinTAI.h	\
	CompletedCellinTAI-Item.h	\
	TBCD-STRING.h	\
	TargetID.h	\
	TargeteNB-ID.h	\
	TargetRNC-ID.h	\
	TargeteNB-ToSourceeNB-TransparentContainer.h	\
	Target-ToSource-TransparentContainer.h	\
	TargetRNC-ToSourceRNC-TransparentContainer.h	\
	TargetBSS-ToSourceBSS-TransparentContainer.h	\
	M1ThresholdEventA2.h	\
	Threshold-RSRP.h	\
	Threshold-RSRQ.h	\
	TimeToWait.h	\
	Time-UE-StayedInCell.h	\
	Time-UE-StayedInCell-EnhancedGranularity.h	\
	TransportInformation.h	\
	TransportLayerAddress.h	\
	TraceActivation.h	\
	TraceDepth.h	\
	E-UTRAN-Trace-ID.h	\
	TrafficLoadReductionIndication.h	\
	TunnelInformation.h	\
	TypeOfError.h	\
	TAIListForRestart.h	\
	UEAggregateMaximumBitrate.h	\
	UE-RetentionInformation.h	\
	UE-S1AP-IDs.h	\
	UE-S1AP-ID-pair.h	\
	UE-associatedLogicalS1-ConnectionItem.h	\
	UEIdentityIndexValue.h	\
	UE-HistoryInformation.h	\
	UE-HistoryInformationFromTheUE.h	\
	UEPagingID.h	\
	UERadioCapability.h	\
	UERadioCapabilityForPaging.h	\
	UE-RLF-Report-Container.h	\
	UE-RLF-Report-Container-for-extended-bands.h	\
	UESecurityCapabilities.h	\
	UESidelinkAggregateMaximumBitrate.h	\
	UE-Usage-Type.h	\
	UserLocationInformation.h	\
	UEUserPlaneCIoTSupportIndicator.h	\
	VoiceSupportMatchIndicator.h	\
	V2XServicesAuthorized.h	\
	VehicleUE.h	\
	PedestrianUE.h	\
	WarningAreaList.h	\
	WarningType.h	\
	WarningSecurityInfo.h	\
	WarningMessageContents.h	\
	X2TNLConfigurationInfo.h	\
	ENBX2ExtTLAs.h	\
	ENBX2ExtTLA.h	\
	ENBX2GTPTLAs.h	\
	ENBIndirectX2TransportLayerAddresses.h	\
	Criticality.h	\
	Presence.h	\
	PrivateIE-ID.h	\
	ProcedureCode.h	\
	ProtocolExtensionID.h	\
	ProtocolIE-ID.h	\
	TriggeringMessage.h	\
	ProtocolIE-Container.h	\
	ProtocolIE-SingleContainer.h	\
	ProtocolIE-Field.h	\
	ProtocolIE-ContainerPair.h	\
	ProtocolIE-FieldPair.h	\
	ProtocolIE-ContainerList.h	\
	ProtocolIE-ContainerPairList.h	\
	ProtocolExtensionContainer.h	\
	ProtocolExtensionField.h	\
	PrivateIE-Container.h	\
	PrivateIE-Field.h	\
	SONtransferApplicationIdentity.h	\
	SONtransferRequestContainer.h	\
	SONtransferResponseContainer.h	\
	SONtransferCause.h	\
	CellLoadReportingCause.h	\
	HOReportingCause.h	\
	CellActivationCause.h	\
	CellStateIndicationCause.h	\
	FailureEventReportingCause.h	\
	CellLoadReportingResponse.h	\
	CompositeAvailableCapacityGroup.h	\
	EUTRANcellLoadReportingResponse.h	\
	EUTRANResponse.h	\
	EHRPD-Sector-ID.h	\
	IRAT-Cell-ID.h	\
	RequestedCellList.h	\
	MultiCellLoadReportingRequest.h	\
	ReportingCellList-Item.h	\
	ReportingCellList.h	\
	MultiCellLoadReportingResponse.h	\
	MultiCellLoadReportingResponse-Item.h	\
	NumberOfMeasurementReportingLevels.h	\
	EventTriggeredCellLoadReportingRequest.h	\
	OverloadFlag.h	\
	EventTriggeredCellLoadReportingResponse.h	\
	HOReport.h	\
	HoType.h	\
	HoReportType.h	\
	CandidateCellList.h	\
	CandidatePCIList.h	\
	CandidatePCI.h	\
	CellActivationRequest.h	\
	CellsToActivateList.h	\
	CellsToActivateList-Item.h	\
	CellActivationResponse.h	\
	ActivatedCellsList.h	\
	ActivatedCellsList-Item.h	\
	CellStateIndication.h	\
	NotificationCellList.h	\
	NotificationCellList-Item.h	\
	NotifyFlag.h	\
	FailureEventReport.h	\
	TooEarlyInterRATHOReportReportFromEUTRAN.h	\
	SonTransfer-IEs_MobilityInformation.h	\
	EHRPDCapacityValue.h	\
	EHRPDSectorCapacityClassValue.h	\
	EHRPDSectorLoadReportingResponse.h	\
	EHRPDCompositeAvailableCapacity.h	\
	EHRPDMultiSectorLoadReportingResponseItem.h	\
	EXTERNAL.h

ASN_MODULE_HEADERS+=ANY.h
ASN_MODULE_SOURCES+=ANY.c
ASN_MODULE_HEADERS+=BOOLEAN.h
ASN_MODULE_SOURCES+=BOOLEAN.c
ASN_MODULE_HEADERS+=INTEGER.h
ASN_MODULE_HEADERS+=NativeEnumerated.h
ASN_MODULE_HEADERS+=GraphicString.h
ASN_MODULE_SOURCES+=GraphicString.c
ASN_MODULE_SOURCES+=INTEGER.c
ASN_MODULE_HEADERS+=NULL.h
ASN_MODULE_SOURCES+=NULL.c
ASN_MODULE_SOURCES+=NativeEnumerated.c
ASN_MODULE_HEADERS+=NativeInteger.h
ASN_MODULE_SOURCES+=NativeInteger.c
ASN_MODULE_HEADERS+=OBJECT_IDENTIFIER.h
ASN_MODULE_SOURCES+=OBJECT_IDENTIFIER.c
ASN_MODULE_HEADERS+=ObjectDescriptor.h
ASN_MODULE_SOURCES+=ObjectDescriptor.c
ASN_MODULE_HEADERS+=PrintableString.h
ASN_MODULE_SOURCES+=PrintableString.c
ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=asn_SET_OF.h
ASN_MODULE_SOURCES+=asn_SET_OF.c
ASN_MODULE_HEADERS+=constr_CHOICE.h
ASN_MODULE_SOURCES+=constr_CHOICE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE.h
ASN_MODULE_SOURCES+=constr_SEQUENCE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=constr_SET_OF.h
ASN_MODULE_SOURCES+=constr_SET_OF.c
ASN_MODULE_HEADERS+=asn_application.h
ASN_MODULE_HEADERS+=asn_system.h
ASN_MODULE_HEADERS+=asn_codecs.h
ASN_MODULE_HEADERS+=asn_internal.h
ASN_MODULE_HEADERS+=OCTET_STRING.h
ASN_MODULE_SOURCES+=OCTET_STRING.c
ASN_MODULE_HEADERS+=BIT_STRING.h
ASN_MODULE_SOURCES+=BIT_STRING.c
ASN_MODULE_SOURCES+=asn_codecs_prim.c
ASN_MODULE_HEADERS+=asn_codecs_prim.h
ASN_MODULE_HEADERS+=ber_tlv_length.h
ASN_MODULE_SOURCES+=ber_tlv_length.c
ASN_MODULE_HEADERS+=ber_tlv_tag.h
ASN_MODULE_SOURCES+=ber_tlv_tag.c
ASN_MODULE_HEADERS+=ber_decoder.h
ASN_MODULE_SOURCES+=ber_decoder.c
ASN_MODULE_HEADERS+=der_encoder.h
ASN_MODULE_SOURCES+=der_encoder.c
ASN_MODULE_HEADERS+=constr_TYPE.h
ASN_MODULE_SOURCES+=constr_TYPE.c
ASN_MODULE_HEADERS+=constraints.h
ASN_MODULE_SOURCES+=constraints.c
ASN_MODULE_HEADERS+=xer_support.h
ASN_MODULE_SOURCES+=xer_support.c
ASN_MODULE_HEADERS+=xer_decoder.h
ASN_MODULE_SOURCES+=xer_decoder.c
ASN_MODULE_HEADERS+=xer_encoder.h
ASN_MODULE_SOURCES+=xer_encoder.c
ASN_MODULE_HEADERS+=per_support.h
ASN_MODULE_SOURCES+=per_support.c
ASN_MODULE_HEADERS+=per_decoder.h
ASN_MODULE_SOURCES+=per_decoder.c
ASN_MODULE_HEADERS+=per_encoder.h
ASN_MODULE_SOURCES+=per_encoder.c
ASN_MODULE_HEADERS+=per_opentype.h
ASN_MODULE_SOURCES+=per_opentype.c
ASN_CONVERTER_SOURCES+=converter-sample.c
ASN_CONVERTER_SOURCES+=pdu_collection.c


lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = s1ap-dump
CFLAGS += -DJUNKTEST  -DPDU=S1AP_PDU -DASN_PDU_COLLECTION -I.
OBJS=${ASN_MODULE_SOURCES:.c=.o} ${ASN_CONVERTER_SOURCES:.c=.o}

all: S1AP-PDU.c $(TARGET)

$(TARGET): ${OBJS}
	$(CC) $(CFLAGS) -o $(TARGET) ${OBJS} $(LDFLAGS) $(LIBS)

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJS)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	../../asn1c/asn1c -S ../../skeletons -pdu=S1AP-PDU -pdu=auto -fcompound-names -gen-PER ../s1ap-14.2.0.asn1


S1AP-PDU.c: ../sample.makefile.regen ../s1ap-14.2.0.asn1
	make regen-makefile
	@touch S1AP-PDU.c
	make

regen-makefile:
	ASN1CMDOPTS="-pdu=auto -fcompound-names -gen-PER" \
	ASN1MODULES="../s1ap-14.2.0.asn1" \
	ASN1PDU=S1AP-PDU \
	PROGNAME=s1ap-dump \
	CFLAGS="" \
	../sample.makefile.regen

check: ${TARGET} check-ber check-xer check-per
	@echo ================
	@echo All tests passed
	@echo ================

check-ber:
	@if test -f sample-S1AP-PDU-1.[db]er ; then \
	for f in sample-S1AP-PDU-*.[db]er; do \
	for b in 1 17 33 980 8192; do \
	echo "Recoding $$f into XER and back ($$b)..."; \
	./${TARGET} -b $$b -iber -oxer $$f > ./.tmp.1.$$$$ || exit 2; \
	./${TARGET} -b $$b -ixer -oxer ./.tmp.1.$$$$ > ./.tmp.2.$$$$ || exit 3; \
	diff ./.tmp.1.$$$$ ./.tmp.2.$$$$ || exit 4; \
	rm -f ./.tmp.[12].$$$$; \
	echo "Test junking $$f (please wait)..."; \
	./${TARGET} -J0.0001 -n 1000 -b $$b -iber -onull $$f || exit 5; \
	./${TARGET} -J0.001 -n 1000 -b $$b -iber -onull $$f || exit 6; \
	done; done; fi

check-xer:
	@if test -f sample-S1AP-PDU-1.xer ; then \
	for f in sample-S1AP-PDU-*.xer; do \
	for b in 1 17 33 980 8192; do \
	echo "Recoding $$f into DER and back ($$b)..."; \
	./${TARGET} -b $$b -ixer -oder $$f > ./.tmp.1.$$$$ || exit 2; \
	./${TARGET} -b $$b -iber -oxer ./.tmp.1.$$$$ > ./.tmp.2.$$$$ || exit 3; \
	diff $$f ./.tmp.2.$$$$ || exit 4; \
	rm -f ./.tmp.[12].$$$$; \
	echo "Test junking $$f (please wait)..."; \
	./${TARGET} -J0.0001 -n 1000 -b $$b -ixer -onull $$f || exit 5; \
	./${TARGET} -J0.001 -n 1000 -b $$b -ixer -onull $$f || exit 6; \
	done; done; fi

check-per:
	@if test -f sample-S1AP-PDU-1-nopad.per ; then \
	for f in sample-S1AP-PDU-[1-9]-nopad.per; do \
	for b in 1 17 33 980 8192; do \
	echo "Recoding non-padded $$f into DER into XER and back ($$b)..."; \
	./${TARGET} -b $$b -per-nopad -iper -oder $$f > ./.tmp.1.$$$$ || exit 2; \
	./${TARGET} -b $$b -iber -oxer ./.tmp.1.$$$$ > ./.tmp.2.$$$$ || exit 3; \
	./${TARGET} -b $$b -ixer -oder ./.tmp.2.$$$$ > ./.tmp.3.$$$$ || exit 4; \
	diff ./.tmp.1.$$$$ ./.tmp.3.$$$$ || exit 5; \
	rm -f ./.tmp.[123].$$$$; \
	echo "Test junking $$f (please wait)..."; \
	./${TARGET} -J0.0001 -n 1000 -b $$b -per-nopad -iper -onull $$f || exit 6; \
	./${TARGET} -J0.001 -n 1000 -b $$b -per-nopad -iper -onull $$f || exit 7; \
	done; done; fi
	@if test -f sample-S1AP-PDU-1.per ; then \
	for f in sample-*-[1-9].per; do \
	pdu=`echo $$f | sed -E -e "s/sample-([A-Za-z-]+)-[0-9].*/\1/"`; \
	for b in 1 17 33 980 8192; do \
	echo "Recoding $$f into DER into XER and back ($$b)..."; \
	./${TARGET} -b $$b -p $$pdu -iper -oder $$f > ./.tmp.1.$$$$ || exit 3; \
	./${TARGET} -b $$b -p $$pdu -iber -oxer ./.tmp.1.$$$$ > ./.tmp.2.$$$$ || exit 4; \
	./${TARGET} -b $$b -p $$pdu -ixer -oper ./.tmp.2.$$$$ > ./.tmp.1.$$$$ || exit 5; \
	diff $$f ./.tmp.1.$$$$ || exit 6; \
	rm -f ./.tmp.[12].$$$$; \
	echo "Test junking $$f (please wait)..."; \
	./${TARGET} -J0.0001 -n 1000 -b $$b -iper -onull $$f || exit 7; \
	./${TARGET} -J0.001 -n 1000 -b $$b -iper -onull $$f || exit 8; \
	done; done; fi

distclean: clean
	rm -f $(ASN_MODULE_SOURCES)
	rm -f $(ASN_MODULE_HEADERS)
	rm -f $(ASN_CONVERTER_SOURCES) $(ASN_CONVERTER_HEADERS)
	rm -f Makefile.am.sample
