ASN_MODULE_SOURCES=	\
	RANAP-PDU.c	\
	InitiatingMessage.c	\
	SuccessfulOutcome.c	\
	UnsuccessfulOutcome.c	\
	Outcome.c	\
	RAB-IE-ContainerList.c	\
	RAB-IE-ContainerPairList.c	\
	ProtocolError-IE-ContainerList.c	\
	IuSigConId-IE-ContainerList.c	\
	DirectTransfer-IE-ContainerList.c	\
	Iu-ReleaseCommand.c	\
	Iu-ReleaseComplete.c	\
	RAB-DataVolumeReportList.c	\
	RAB-DataVolumeReportItem.c	\
	RAB-ReleasedList-IuRelComp.c	\
	RAB-ReleasedItem-IuRelComp.c	\
	RelocationRequired.c	\
	RelocationCommand.c	\
	RAB-RelocationReleaseList.c	\
	RAB-RelocationReleaseItem.c	\
	RAB-DataForwardingList.c	\
	RAB-DataForwardingItem.c	\
	RelocationPreparationFailure.c	\
	RelocationRequest.c	\
	RAB-SetupList-RelocReq.c	\
	RAB-SetupItem-RelocReq.c	\
	UserPlaneInformation.c	\
	CNMBMSLinkingInformation.c	\
	JoinedMBMSBearerService-IEs.c	\
	RelocationRequestAcknowledge.c	\
	RAB-SetupList-RelocReqAck.c	\
	RAB-SetupItem-RelocReqAck.c	\
	RAB-FailedList.c	\
	RAB-FailedItem.c	\
	RelocationFailure.c	\
	RelocationCancel.c	\
	RelocationCancelAcknowledge.c	\
	SRNS-ContextRequest.c	\
	RAB-DataForwardingList-SRNS-CtxReq.c	\
	RAB-DataForwardingItem-SRNS-CtxReq.c	\
	SRNS-ContextResponse.c	\
	RAB-ContextList.c	\
	RAB-ContextItem.c	\
	RAB-ContextFailedtoTransferList.c	\
	RABs-ContextFailedtoTransferItem.c	\
	SecurityModeCommand.c	\
	SecurityModeComplete.c	\
	SecurityModeReject.c	\
	DataVolumeReportRequest.c	\
	RAB-DataVolumeReportRequestList.c	\
	RAB-DataVolumeReportRequestItem.c	\
	DataVolumeReport.c	\
	RAB-FailedtoReportList.c	\
	RABs-failed-to-reportItem.c	\
	Reset.c	\
	ResetAcknowledge.c	\
	ResetResource.c	\
	ResetResourceList.c	\
	ResetResourceItem.c	\
	ResetResourceAcknowledge.c	\
	ResetResourceAckList.c	\
	ResetResourceAckItem.c	\
	RAB-ReleaseRequest.c	\
	RAB-ReleaseList.c	\
	RAB-ReleaseItem.c	\
	Iu-ReleaseRequest.c	\
	RelocationDetect.c	\
	RelocationComplete.c	\
	EnhancedRelocationCompleteRequest.c	\
	RAB-SetupList-EnhancedRelocCompleteReq.c	\
	RAB-SetupItem-EnhancedRelocCompleteReq.c	\
	EnhancedRelocationCompleteResponse.c	\
	RAB-SetupList-EnhancedRelocCompleteRes.c	\
	RAB-SetupItem-EnhancedRelocCompleteRes.c	\
	RAB-ToBeReleasedList-EnhancedRelocCompleteRes.c	\
	RAB-ToBeReleasedItem-EnhancedRelocCompleteRes.c	\
	EnhancedRelocationCompleteFailure.c	\
	EnhancedRelocationCompleteConfirm.c	\
	Paging.c	\
	CommonID.c	\
	CN-InvokeTrace.c	\
	CN-DeactivateTrace.c	\
	LocationReportingControl.c	\
	LocationReport.c	\
	InitialUE-Message.c	\
	DirectTransfer.c	\
	RedirectionIndication.c	\
	Overload.c	\
	ErrorIndication.c	\
	SRNS-DataForwardCommand.c	\
	ForwardSRNS-Context.c	\
	RAB-AssignmentRequest.c	\
	RAB-SetupOrModifyList.c	\
	RAB-SetupOrModifyItemFirst.c	\
	TransportLayerInformation.c	\
	RAB-SetupOrModifyItemSecond.c	\
	RAB-AssignmentResponse.c	\
	RAB-SetupOrModifiedList.c	\
	RAB-SetupOrModifiedItem.c	\
	RAB-ReleasedList.c	\
	RAB-ReleasedItem.c	\
	DataVolumeList.c	\
	RAB-QueuedList.c	\
	RAB-QueuedItem.c	\
	RAB-ReleaseFailedList.c	\
	GERAN-Iumode-RAB-FailedList-RABAssgntResponse.c	\
	GERAN-Iumode-RAB-Failed-RABAssgntResponse-Item.c	\
	PrivateMessage.c	\
	RANAP-RelocationInformation.c	\
	DirectTransferInformationList-RANAP-RelocInf.c	\
	DirectTransferInformationItem-RANAP-RelocInf.c	\
	RAB-ContextList-RANAP-RelocInf.c	\
	RAB-ContextItem-RANAP-RelocInf.c	\
	RANAP-EnhancedRelocationInformationRequest.c	\
	RAB-SetupList-EnhRelocInfoReq.c	\
	RAB-SetupItem-EnhRelocInfoReq.c	\
	TNLInformationEnhRelInfoReq.c	\
	RANAP-EnhancedRelocationInformationResponse.c	\
	RAB-SetupList-EnhRelocInfoRes.c	\
	RAB-SetupItem-EnhRelocInfoRes.c	\
	RAB-FailedList-EnhRelocInfoRes.c	\
	RAB-FailedItem-EnhRelocInfoRes.c	\
	TNLInformationEnhRelInfoRes.c	\
	RAB-ModifyRequest.c	\
	RAB-ModifyList.c	\
	RAB-ModifyItem.c	\
	LocationRelatedDataRequest.c	\
	LocationRelatedDataResponse.c	\
	LocationRelatedDataFailure.c	\
	InformationTransferIndication.c	\
	InformationTransferConfirmation.c	\
	InformationTransferFailure.c	\
	UESpecificInformationIndication.c	\
	DirectInformationTransfer.c	\
	UplinkInformationExchangeRequest.c	\
	UplinkInformationExchangeResponse.c	\
	UplinkInformationExchangeFailure.c	\
	MBMSSessionStart.c	\
	MBMSSynchronisationInformation.c	\
	MBMSSessionStartResponse.c	\
	MBMSSessionStartFailure.c	\
	MBMSSessionUpdate.c	\
	MBMSSessionUpdateResponse.c	\
	MBMSSessionUpdateFailure.c	\
	MBMSSessionStop.c	\
	MBMSSessionStopResponse.c	\
	MBMSUELinkingRequest.c	\
	LeftMBMSBearerService-IEs.c	\
	MBMSUELinkingResponse.c	\
	UnsuccessfulLinking-IEs.c	\
	MBMSRegistrationRequest.c	\
	MBMSRegistrationResponse.c	\
	MBMSRegistrationFailure.c	\
	MBMSCNDe-RegistrationRequest.c	\
	MBMSCNDe-RegistrationResponse.c	\
	MBMSRABEstablishmentIndication.c	\
	MBMSRABReleaseRequest.c	\
	MBMSRABRelease.c	\
	MBMSRABReleaseFailure.c	\
	SRVCC-CSKeysRequest.c	\
	SRVCC-CSKeysResponse.c	\
	UeRadioCapabilityMatchRequest.c	\
	UeRadioCapabilityMatchResponse.c	\
	UeRegistrationQueryRequest.c	\
	UeRegistrationQueryResponse.c	\
	RerouteNASRequest.c	\
	RANAP-Message.c	\
	AccuracyFulfilmentIndicator.c	\
	Additional-CSPS-coordination-information.c	\
	Additional-PositioningDataSet.c	\
	Additional-PositioningMethodAndUsage.c	\
	AllocationOrRetentionPriority.c	\
	Alt-RAB-Parameters.c	\
	Alt-RAB-Parameter-ExtendedGuaranteedBitrateInf.c	\
	Alt-RAB-Parameter-ExtendedGuaranteedBitrates.c	\
	Alt-RAB-Parameter-ExtendedGuaranteedBitrateList.c	\
	Alt-RAB-Parameter-GuaranteedBitrateInf.c	\
	Alt-RAB-Parameter-GuaranteedBitrateType.c	\
	Alt-RAB-Parameter-GuaranteedBitrates.c	\
	Alt-RAB-Parameter-GuaranteedBitrateList.c	\
	Alt-RAB-Parameter-SupportedGuaranteedBitrateInf.c	\
	Alt-RAB-Parameter-SupportedGuaranteedBitrates.c	\
	Alt-RAB-Parameter-ExtendedMaxBitrateInf.c	\
	Alt-RAB-Parameter-ExtendedMaxBitrates.c	\
	Alt-RAB-Parameter-ExtendedMaxBitrateList.c	\
	Alt-RAB-Parameter-MaxBitrateInf.c	\
	Alt-RAB-Parameter-MaxBitrateType.c	\
	Alt-RAB-Parameter-MaxBitrates.c	\
	Alt-RAB-Parameter-MaxBitrateList.c	\
	Alt-RAB-Parameter-SupportedMaxBitrateInf.c	\
	Alt-RAB-Parameter-SupportedMaxBitrates.c	\
	AlternativeRABConfigurationRequest.c	\
	UE-Application-Layer-Measurement-Configuration.c	\
	UE-Application-Layer-Measurement-Configuration-For-Relocation.c	\
	APN.c	\
	AreaScopeForUEApplicationLayerMeasurementConfiguration.c	\
	AreaIdentity.c	\
	Ass-RAB-Parameters.c	\
	Ass-RAB-Parameter-ExtendedGuaranteedBitrateList.c	\
	Ass-RAB-Parameter-ExtendedMaxBitrateList.c	\
	Ass-RAB-Parameter-GuaranteedBitrateList.c	\
	Ass-RAB-Parameter-MaxBitrateList.c	\
	AuthorisedPLMNs.c	\
	AuthorisedSNAs.c	\
	BarometricPressure.c	\
	BindingID.c	\
	BroadcastAssistanceDataDecipheringKeys.c	\
	Cause.c	\
	CauseMisc.c	\
	CauseNAS.c	\
	CauseProtocol.c	\
	CauseRadioNetwork.c	\
	CauseRadioNetworkExtension.c	\
	CauseNon-Standard.c	\
	CauseTransmissionNetwork.c	\
	Cell-Access-Mode.c	\
	CellBased.c	\
	CellIdList.c	\
	Cell-Id.c	\
	Cell-Capacity-Class-Value.c	\
	CellLoadInformation.c	\
	CellLoadInformationGroup.c	\
	CellType.c	\
	CivicAddress.c	\
	ClientType.c	\
	CriticalityDiagnostics.c	\
	CriticalityDiagnostics-IE-List.c	\
	MessageStructure.c	\
	CGI.c	\
	ChosenEncryptionAlgorithm.c	\
	ChosenIntegrityProtectionAlgorithm.c	\
	CI.c	\
	ClassmarkInformation2.c	\
	ClassmarkInformation3.c	\
	CN-DomainIndicator.c	\
	CN-ID.c	\
	Correlation-ID.c	\
	CSFB-Information.c	\
	CSG-Id.c	\
	CSG-Id-List.c	\
	CSG-Membership-Status.c	\
	DataPDUType.c	\
	DataVolumeReference.c	\
	DataVolumeReportingIndication.c	\
	DCH-ID.c	\
	DCN-ID.c	\
	DeliveryOfErroneousSDU.c	\
	DeliveryOrder.c	\
	DeltaRAListofIdleModeUEs.c	\
	NewRAListofIdleModeUEs.c	\
	RAListwithNoIdleModeUEsAnyMore.c	\
	ForwardingIndication.c	\
	DL-GTP-PDU-SequenceNumber.c	\
	DL-N-PDU-SequenceNumber.c	\
	D-RNTI.c	\
	DRX-CycleLengthCoefficient.c	\
	DSCH-ID.c	\
	EARFCN-Extended.c	\
	E-DCH-MAC-d-Flow-ID.c	\
	ENB-ID.c	\
	EncryptionAlgorithm.c	\
	EncryptionInformation.c	\
	EncryptionKey.c	\
	End-Of-CSFB.c	\
	EquipmentsToBeTraced.c	\
	E-UTRAN-Service-Handover.c	\
	Event.c	\
	Event1F-Parameters.c	\
	Event1I-Parameters.c	\
	ExtendedGuaranteedBitrate.c	\
	ExtendedMaxBitrate.c	\
	ExtendedRNC-ID.c	\
	FrameSequenceNumber.c	\
	FrequenceLayerConvergenceFlag.c	\
	GANSS-PositioningDataSet.c	\
	GANSS-PositioningMethodAndUsage.c	\
	GeographicalArea.c	\
	GeographicalCoordinates.c	\
	GA-AltitudeAndDirection.c	\
	GA-EllipsoidArc.c	\
	GA-Point.c	\
	GA-PointWithAltitude.c	\
	GA-PointWithAltitudeAndUncertaintyEllipsoid.c	\
	GA-PointWithUnCertainty.c	\
	GA-PointWithUnCertaintyEllipse.c	\
	GA-Polygon.c	\
	GA-UncertaintyEllipse.c	\
	GERAN-BSC-Container.c	\
	GERAN-Cell-ID.c	\
	GERAN-Classmark.c	\
	GlobalCN-ID.c	\
	GlobalRNC-ID.c	\
	GTP-TEI.c	\
	GuaranteedBitrate.c	\
	HigherBitratesThan16MbpsFlag.c	\
	HS-DSCH-MAC-d-Flow-ID.c	\
	IMEI.c	\
	IMEIGroup.c	\
	IMEIList.c	\
	IMEISV.c	\
	IMEISVGroup.c	\
	IMEISVList.c	\
	ImmediateMDT.c	\
	IMSI.c	\
	IncludeVelocity.c	\
	InformationExchangeID.c	\
	InformationExchangeType.c	\
	InformationRequested.c	\
	InformationRequestType.c	\
	InformationTransferID.c	\
	InformationTransferType.c	\
	IntegrityProtectionAlgorithm.c	\
	IntegrityProtectionInformation.c	\
	IntegrityProtectionKey.c	\
	InterSystemInformationTransferType.c	\
	InterSystemInformation-TransparentContainer.c	\
	IPMulticastAddress.c	\
	IuSignallingConnectionIdentifier.c	\
	IuTransportAssociation.c	\
	KeyStatus.c	\
	LA-LIST.c	\
	LAC.c	\
	LAI.c	\
	LastKnownServiceArea.c	\
	LastVisitedUTRANCell-Item.c	\
	LHN-ID.c	\
	Links-to-log.c	\
	ListOF-SNAs.c	\
	ListOfInterfacesToTrace.c	\
	InterfacesToTraceItem.c	\
	LoadValue.c	\
	LocationRelatedDataRequestType.c	\
	LocationRelatedDataRequestTypeSpecificToGERANIuMode.c	\
	LocationReportingTransferInformation.c	\
	ReportChangeOfSAI.c	\
	PeriodicReportingIndicator.c	\
	DirectReportingIndicator.c	\
	L3-Information.c	\
	M1Report.c	\
	M2Report.c	\
	M4Report.c	\
	M4-Collection-Parameters.c	\
	M4-Period.c	\
	M4-Threshold.c	\
	M5Report.c	\
	M5-Period.c	\
	M6Report.c	\
	M6-Period.c	\
	M7Report.c	\
	M7-Period.c	\
	Management-Based-MDT-Allowed.c	\
	MaxBitrate.c	\
	MaxSDU-Size.c	\
	MBMS-PTP-RAB-ID.c	\
	MBMSBearerServiceType.c	\
	MBMSCNDe-Registration.c	\
	MBMSCountingInformation.c	\
	MBMSHCIndicator.c	\
	MBMSIPMulticastAddressandAPNRequest.c	\
	MBMSLinkingInformation.c	\
	MBMSRegistrationRequestType.c	\
	MBMSServiceArea.c	\
	MBMSSessionDuration.c	\
	MBMSSessionIdentity.c	\
	MBMSSessionRepetitionNumber.c	\
	MDT-Activation.c	\
	MDTAreaScope.c	\
	MDT-Configuration.c	\
	MDTMode.c	\
	MDT-PLMN-List.c	\
	MDT-Report-Parameters.c	\
	MeasurementQuantity.c	\
	MeasurementsToActivate.c	\
	MSISDN.c	\
	NAS-PDU.c	\
	NAS-SequenceNumber.c	\
	NAS-SynchronisationIndicator.c	\
	NewBSS-To-OldBSS-Information.c	\
	NonSearchingIndication.c	\
	NRTLoadInformationValue.c	\
	Null-NRI.c	\
	NumberOfIuInstances.c	\
	NumberOfSteps.c	\
	Offload-RAB-Parameters.c	\
	Offload-RAB-Parameters-APN.c	\
	Offload-RAB-Parameters-ChargingCharacteristics.c	\
	OldBSS-ToNewBSS-Information.c	\
	OMC-ID.c	\
	Out-Of-UTRAN.c	\
	PagingAreaID.c	\
	PagingCause.c	\
	PDP-TypeInformation.c	\
	PDP-Type.c	\
	PDP-TypeInformation-extension.c	\
	PDP-Type-extension.c	\
	PDUType14FrameSequenceNumber.c	\
	PeriodicLocationInfo.c	\
	PermanentNAS-UE-ID.c	\
	PermittedEncryptionAlgorithms.c	\
	PermittedIntegrityProtectionAlgorithms.c	\
	LABased.c	\
	LAI-List.c	\
	LoggedMDT.c	\
	LoggingInterval.c	\
	LoggingDuration.c	\
	PLMNBased.c	\
	PLMNList.c	\
	PLMNidentity.c	\
	PLMNs-in-shared-network.c	\
	Port-Number.c	\
	PositioningDataDiscriminator.c	\
	PositioningDataSet.c	\
	PositioningMethodAndUsage.c	\
	PositioningPriority.c	\
	PositionData.c	\
	PositionDataSpecificToGERANIuMode.c	\
	Pre-emptionCapability.c	\
	Pre-emptionVulnerability.c	\
	PriorityLevel.c	\
	Priority-Class-Indicator.c	\
	ProvidedData.c	\
	PowerSavingIndicator.c	\
	P-TMSI.c	\
	QueuingAllowed.c	\
	RAB-AsymmetryIndicator.c	\
	RABased.c	\
	RAI-List.c	\
	RABDataVolumeReport.c	\
	RAB-ID.c	\
	RAB-Parameter-ExtendedGuaranteedBitrateList.c	\
	RAB-Parameter-ExtendedMaxBitrateList.c	\
	RAB-Parameter-GuaranteedBitrateList.c	\
	RAB-Parameter-MaxBitrateList.c	\
	RAB-Parameters.c	\
	RABParametersList.c	\
	RAB-SubflowCombinationBitRate.c	\
	RAB-TrCH-Mapping.c	\
	RAB-TrCH-MappingItem.c	\
	RAC.c	\
	RAI.c	\
	RAListofIdleModeUEs.c	\
	NotEmptyRAListofIdleModeUEs.c	\
	RAofIdleModeUEs.c	\
	LAListofIdleModeUEs.c	\
	RAT-Type.c	\
	RateControlAllowed.c	\
	RedirectAttemptFlag.c	\
	RedirectionCompleted.c	\
	RejectCauseValue.c	\
	RelocationRequirement.c	\
	RelocationType.c	\
	RepetitionNumber0.c	\
	RepetitionNumber1.c	\
	ReportArea.c	\
	ReportInterval.c	\
	ReportAmount.c	\
	RequestedGPSAssistanceData.c	\
	RequestedGANSSAssistanceData.c	\
	RequestedLocationRelatedDataType.c	\
	RequestedMBMSIPMulticastAddressandAPNRequest.c	\
	MBMSIPMulticastAddressandAPNlist.c	\
	RequestedMulticastServiceList.c	\
	Requested-RAB-Parameter-Values.c	\
	Requested-RAB-Parameter-ExtendedMaxBitrateList.c	\
	Requested-RAB-Parameter-ExtendedGuaranteedBitrateList.c	\
	Requested-RAB-Parameter-MaxBitrateList.c	\
	Requested-RAB-Parameter-GuaranteedBitrateList.c	\
	RequestType.c	\
	ResidualBitErrorRatio.c	\
	ResponseTime.c	\
	RIMInformation.c	\
	RIM-Transfer.c	\
	RIMRoutingAddress.c	\
	RNC-ID.c	\
	RNCTraceInformation.c	\
	RNSAPRelocationParameters.c	\
	RRC-Container.c	\
	RTLoadValue.c	\
	RSRVCC-HO-Indication.c	\
	RSRVCC-Information.c	\
	RSRVCC-Operation-Possible.c	\
	SAC.c	\
	SAI.c	\
	SAPI.c	\
	SessionUpdateID.c	\
	Shared-Network-Information.c	\
	Session-Re-establishment-Indicator.c	\
	SignallingIndication.c	\
	SDU-ErrorRatio.c	\
	SDU-FormatInformationParameters.c	\
	SDU-Parameters.c	\
	SGSN-Group-Identity.c	\
	SGSN-Group-ID.c	\
	SNA-Access-Information.c	\
	SNAC.c	\
	Service-Handover.c	\
	Source-ToTarget-TransparentContainer.c	\
	SourceeNodeB-ToTargeteNodeB-TransparentContainer.c	\
	SourceCellID.c	\
	SourceBSS-ToTargetBSS-TransparentContainer.c	\
	SourceID.c	\
	SourceRNC-ID.c	\
	SourceRNC-ToTargetRNC-TransparentContainer.c	\
	IRAT-Measurement-Configuration.c	\
	IRATmeasurementParameters.c	\
	RSRQ-Type.c	\
	RSRQ-Extension.c	\
	EUTRANFrequencies.c	\
	MeasBand.c	\
	SubscriberProfileIDforRFP.c	\
	SourceStatisticsDescriptor.c	\
	SupportedRAB-ParameterBitrateList.c	\
	SupportedBitrate.c	\
	SourceUTRANCellID.c	\
	SRB-ID.c	\
	SRB-TrCH-Mapping.c	\
	SRB-TrCH-MappingItem.c	\
	SRVCC-HO-Indication.c	\
	SRVCC-Information.c	\
	SRVCC-Operation-Possible.c	\
	SubflowSDU-Size.c	\
	TAC.c	\
	TAI.c	\
	Target-ToSource-TransparentContainer.c	\
	TargeteNodeB-ToSourceeNodeB-TransparentContainer.c	\
	TargetBSS-ToSourceBSS-TransparentContainer.c	\
	TargetCellId.c	\
	TargetID.c	\
	TargetENB-ID.c	\
	TargetRNC-ID.c	\
	TargetRNC-ToSourceRNC-TransparentContainer.c	\
	TBCD-STRING.c	\
	TemporaryUE-ID.c	\
	Time-UE-StayedInCell.c	\
	Time-UE-StayedInCell-EnhancedGranularity.c	\
	TimeToMBMSDataTransfer.c	\
	TimingDifferenceULDL.c	\
	TMGI.c	\
	TMSI.c	\
	TraceDepth.c	\
	TraceInformation.c	\
	TracePropagationParameters.c	\
	TraceRecordingSessionInformation.c	\
	TraceRecordingSessionReference.c	\
	TraceReference.c	\
	TraceType.c	\
	TrafficClass.c	\
	TrafficHandlingPriority.c	\
	TransferDelay.c	\
	UnsuccessfullyTransmittedDataVolume.c	\
	TransportLayerAddress.c	\
	TrCH-ID.c	\
	TrCH-ID-List.c	\
	TriggerID.c	\
	TunnelInformation.c	\
	TypeOfError.c	\
	UE-AggregateMaximumBitRate.c	\
	UE-AggregateMaximumBitRateDownlink.c	\
	UE-AggregateMaximumBitRateUplink.c	\
	UE-History-Information.c	\
	UE-ID.c	\
	UE-IsNotServed.c	\
	UE-IsServed.c	\
	UE-Usage-Type.c	\
	UERegistrationQueryResult.c	\
	UESBI-Iu.c	\
	UESBI-IuA.c	\
	UESBI-IuB.c	\
	UL-GTP-PDU-SequenceNumber.c	\
	UL-N-PDU-SequenceNumber.c	\
	UPInformation.c	\
	UPInitialisationFrame.c	\
	UP-ModeVersions.c	\
	USCH-ID.c	\
	UserPlaneMode.c	\
	UTRAN-CellID.c	\
	VelocityEstimate.c	\
	HorizontalVelocity.c	\
	HorizontalWithVerticalVelocity.c	\
	HorizontalVelocityWithUncertainty.c	\
	HorizontalWithVerticalVelocityAndUncertainty.c	\
	HorizontalSpeedAndBearing.c	\
	VerticalVelocity.c	\
	VerticalSpeedDirection.c	\
	VerticalAccuracyCode.c	\
	VoiceSupportMatchIndicator.c	\
	Criticality.c	\
	Presence.c	\
	PrivateIE-ID.c	\
	ProcedureCode.c	\
	ProtocolExtensionID.c	\
	ProtocolIE-ID.c	\
	TriggeringMessage.c	\
	ProtocolIE-Container.c	\
	ProtocolIE-Field.c	\
	ProtocolIE-ContainerPair.c	\
	ProtocolIE-FieldPair.c	\
	ProtocolIE-ContainerList.c	\
	ProtocolIE-ContainerPairList.c	\
	ProtocolExtensionContainer.c	\
	ProtocolExtensionField.c	\
	PrivateIE-Container.c	\
	PrivateIE-Field.c	\
	EXTERNAL.c

ASN_MODULE_HEADERS=	\
	RANAP-PDU.h	\
	InitiatingMessage.h	\
	SuccessfulOutcome.h	\
	UnsuccessfulOutcome.h	\
	Outcome.h	\
	RAB-IE-ContainerList.h	\
	RAB-IE-ContainerPairList.h	\
	ProtocolError-IE-ContainerList.h	\
	IuSigConId-IE-ContainerList.h	\
	DirectTransfer-IE-ContainerList.h	\
	Iu-ReleaseCommand.h	\
	Iu-ReleaseComplete.h	\
	RAB-DataVolumeReportList.h	\
	RAB-DataVolumeReportItem.h	\
	RAB-ReleasedList-IuRelComp.h	\
	RAB-ReleasedItem-IuRelComp.h	\
	RelocationRequired.h	\
	RelocationCommand.h	\
	RAB-RelocationReleaseList.h	\
	RAB-RelocationReleaseItem.h	\
	RAB-DataForwardingList.h	\
	RAB-DataForwardingItem.h	\
	RelocationPreparationFailure.h	\
	RelocationRequest.h	\
	RAB-SetupList-RelocReq.h	\
	RAB-SetupItem-RelocReq.h	\
	UserPlaneInformation.h	\
	CNMBMSLinkingInformation.h	\
	JoinedMBMSBearerService-IEs.h	\
	RelocationRequestAcknowledge.h	\
	RAB-SetupList-RelocReqAck.h	\
	RAB-SetupItem-RelocReqAck.h	\
	RAB-FailedList.h	\
	RAB-FailedItem.h	\
	RelocationFailure.h	\
	RelocationCancel.h	\
	RelocationCancelAcknowledge.h	\
	SRNS-ContextRequest.h	\
	RAB-DataForwardingList-SRNS-CtxReq.h	\
	RAB-DataForwardingItem-SRNS-CtxReq.h	\
	SRNS-ContextResponse.h	\
	RAB-ContextList.h	\
	RAB-ContextItem.h	\
	RAB-ContextFailedtoTransferList.h	\
	RABs-ContextFailedtoTransferItem.h	\
	SecurityModeCommand.h	\
	SecurityModeComplete.h	\
	SecurityModeReject.h	\
	DataVolumeReportRequest.h	\
	RAB-DataVolumeReportRequestList.h	\
	RAB-DataVolumeReportRequestItem.h	\
	DataVolumeReport.h	\
	RAB-FailedtoReportList.h	\
	RABs-failed-to-reportItem.h	\
	Reset.h	\
	ResetAcknowledge.h	\
	ResetResource.h	\
	ResetResourceList.h	\
	ResetResourceItem.h	\
	ResetResourceAcknowledge.h	\
	ResetResourceAckList.h	\
	ResetResourceAckItem.h	\
	RAB-ReleaseRequest.h	\
	RAB-ReleaseList.h	\
	RAB-ReleaseItem.h	\
	Iu-ReleaseRequest.h	\
	RelocationDetect.h	\
	RelocationComplete.h	\
	EnhancedRelocationCompleteRequest.h	\
	RAB-SetupList-EnhancedRelocCompleteReq.h	\
	RAB-SetupItem-EnhancedRelocCompleteReq.h	\
	EnhancedRelocationCompleteResponse.h	\
	RAB-SetupList-EnhancedRelocCompleteRes.h	\
	RAB-SetupItem-EnhancedRelocCompleteRes.h	\
	RAB-ToBeReleasedList-EnhancedRelocCompleteRes.h	\
	RAB-ToBeReleasedItem-EnhancedRelocCompleteRes.h	\
	EnhancedRelocationCompleteFailure.h	\
	EnhancedRelocationCompleteConfirm.h	\
	Paging.h	\
	CommonID.h	\
	CN-InvokeTrace.h	\
	CN-DeactivateTrace.h	\
	LocationReportingControl.h	\
	LocationReport.h	\
	InitialUE-Message.h	\
	DirectTransfer.h	\
	RedirectionIndication.h	\
	Overload.h	\
	ErrorIndication.h	\
	SRNS-DataForwardCommand.h	\
	ForwardSRNS-Context.h	\
	RAB-AssignmentRequest.h	\
	RAB-SetupOrModifyList.h	\
	RAB-SetupOrModifyItemFirst.h	\
	TransportLayerInformation.h	\
	RAB-SetupOrModifyItemSecond.h	\
	RAB-AssignmentResponse.h	\
	RAB-SetupOrModifiedList.h	\
	RAB-SetupOrModifiedItem.h	\
	RAB-ReleasedList.h	\
	RAB-ReleasedItem.h	\
	DataVolumeList.h	\
	RAB-QueuedList.h	\
	RAB-QueuedItem.h	\
	RAB-ReleaseFailedList.h	\
	GERAN-Iumode-RAB-FailedList-RABAssgntResponse.h	\
	GERAN-Iumode-RAB-Failed-RABAssgntResponse-Item.h	\
	PrivateMessage.h	\
	RANAP-RelocationInformation.h	\
	DirectTransferInformationList-RANAP-RelocInf.h	\
	DirectTransferInformationItem-RANAP-RelocInf.h	\
	RAB-ContextList-RANAP-RelocInf.h	\
	RAB-ContextItem-RANAP-RelocInf.h	\
	RANAP-EnhancedRelocationInformationRequest.h	\
	RAB-SetupList-EnhRelocInfoReq.h	\
	RAB-SetupItem-EnhRelocInfoReq.h	\
	TNLInformationEnhRelInfoReq.h	\
	RANAP-EnhancedRelocationInformationResponse.h	\
	RAB-SetupList-EnhRelocInfoRes.h	\
	RAB-SetupItem-EnhRelocInfoRes.h	\
	RAB-FailedList-EnhRelocInfoRes.h	\
	RAB-FailedItem-EnhRelocInfoRes.h	\
	TNLInformationEnhRelInfoRes.h	\
	RAB-ModifyRequest.h	\
	RAB-ModifyList.h	\
	RAB-ModifyItem.h	\
	LocationRelatedDataRequest.h	\
	LocationRelatedDataResponse.h	\
	LocationRelatedDataFailure.h	\
	InformationTransferIndication.h	\
	InformationTransferConfirmation.h	\
	InformationTransferFailure.h	\
	UESpecificInformationIndication.h	\
	DirectInformationTransfer.h	\
	UplinkInformationExchangeRequest.h	\
	UplinkInformationExchangeResponse.h	\
	UplinkInformationExchangeFailure.h	\
	MBMSSessionStart.h	\
	MBMSSynchronisationInformation.h	\
	MBMSSessionStartResponse.h	\
	MBMSSessionStartFailure.h	\
	MBMSSessionUpdate.h	\
	MBMSSessionUpdateResponse.h	\
	MBMSSessionUpdateFailure.h	\
	MBMSSessionStop.h	\
	MBMSSessionStopResponse.h	\
	MBMSUELinkingRequest.h	\
	LeftMBMSBearerService-IEs.h	\
	MBMSUELinkingResponse.h	\
	UnsuccessfulLinking-IEs.h	\
	MBMSRegistrationRequest.h	\
	MBMSRegistrationResponse.h	\
	MBMSRegistrationFailure.h	\
	MBMSCNDe-RegistrationRequest.h	\
	MBMSCNDe-RegistrationResponse.h	\
	MBMSRABEstablishmentIndication.h	\
	MBMSRABReleaseRequest.h	\
	MBMSRABRelease.h	\
	MBMSRABReleaseFailure.h	\
	SRVCC-CSKeysRequest.h	\
	SRVCC-CSKeysResponse.h	\
	UeRadioCapabilityMatchRequest.h	\
	UeRadioCapabilityMatchResponse.h	\
	UeRegistrationQueryRequest.h	\
	UeRegistrationQueryResponse.h	\
	RerouteNASRequest.h	\
	RANAP-Message.h	\
	AccuracyFulfilmentIndicator.h	\
	Additional-CSPS-coordination-information.h	\
	Additional-PositioningDataSet.h	\
	Additional-PositioningMethodAndUsage.h	\
	AllocationOrRetentionPriority.h	\
	Alt-RAB-Parameters.h	\
	Alt-RAB-Parameter-ExtendedGuaranteedBitrateInf.h	\
	Alt-RAB-Parameter-ExtendedGuaranteedBitrates.h	\
	Alt-RAB-Parameter-ExtendedGuaranteedBitrateList.h	\
	Alt-RAB-Parameter-GuaranteedBitrateInf.h	\
	Alt-RAB-Parameter-GuaranteedBitrateType.h	\
	Alt-RAB-Parameter-GuaranteedBitrates.h	\
	Alt-RAB-Parameter-GuaranteedBitrateList.h	\
	Alt-RAB-Parameter-SupportedGuaranteedBitrateInf.h	\
	Alt-RAB-Parameter-SupportedGuaranteedBitrates.h	\
	Alt-RAB-Parameter-ExtendedMaxBitrateInf.h	\
	Alt-RAB-Parameter-ExtendedMaxBitrates.h	\
	Alt-RAB-Parameter-ExtendedMaxBitrateList.h	\
	Alt-RAB-Parameter-MaxBitrateInf.h	\
	Alt-RAB-Parameter-MaxBitrateType.h	\
	Alt-RAB-Parameter-MaxBitrates.h	\
	Alt-RAB-Parameter-MaxBitrateList.h	\
	Alt-RAB-Parameter-SupportedMaxBitrateInf.h	\
	Alt-RAB-Parameter-SupportedMaxBitrates.h	\
	AlternativeRABConfigurationRequest.h	\
	UE-Application-Layer-Measurement-Configuration.h	\
	UE-Application-Layer-Measurement-Configuration-For-Relocation.h	\
	APN.h	\
	AreaScopeForUEApplicationLayerMeasurementConfiguration.h	\
	AreaIdentity.h	\
	Ass-RAB-Parameters.h	\
	Ass-RAB-Parameter-ExtendedGuaranteedBitrateList.h	\
	Ass-RAB-Parameter-ExtendedMaxBitrateList.h	\
	Ass-RAB-Parameter-GuaranteedBitrateList.h	\
	Ass-RAB-Parameter-MaxBitrateList.h	\
	AuthorisedPLMNs.h	\
	AuthorisedSNAs.h	\
	BarometricPressure.h	\
	BindingID.h	\
	BroadcastAssistanceDataDecipheringKeys.h	\
	Cause.h	\
	CauseMisc.h	\
	CauseNAS.h	\
	CauseProtocol.h	\
	CauseRadioNetwork.h	\
	CauseRadioNetworkExtension.h	\
	CauseNon-Standard.h	\
	CauseTransmissionNetwork.h	\
	Cell-Access-Mode.h	\
	CellBased.h	\
	CellIdList.h	\
	Cell-Id.h	\
	Cell-Capacity-Class-Value.h	\
	CellLoadInformation.h	\
	CellLoadInformationGroup.h	\
	CellType.h	\
	CivicAddress.h	\
	ClientType.h	\
	CriticalityDiagnostics.h	\
	CriticalityDiagnostics-IE-List.h	\
	MessageStructure.h	\
	CGI.h	\
	ChosenEncryptionAlgorithm.h	\
	ChosenIntegrityProtectionAlgorithm.h	\
	CI.h	\
	ClassmarkInformation2.h	\
	ClassmarkInformation3.h	\
	CN-DomainIndicator.h	\
	CN-ID.h	\
	Correlation-ID.h	\
	CSFB-Information.h	\
	CSG-Id.h	\
	CSG-Id-List.h	\
	CSG-Membership-Status.h	\
	DataPDUType.h	\
	DataVolumeReference.h	\
	DataVolumeReportingIndication.h	\
	DCH-ID.h	\
	DCN-ID.h	\
	DeliveryOfErroneousSDU.h	\
	DeliveryOrder.h	\
	DeltaRAListofIdleModeUEs.h	\
	NewRAListofIdleModeUEs.h	\
	RAListwithNoIdleModeUEsAnyMore.h	\
	ForwardingIndication.h	\
	DL-GTP-PDU-SequenceNumber.h	\
	DL-N-PDU-SequenceNumber.h	\
	D-RNTI.h	\
	DRX-CycleLengthCoefficient.h	\
	DSCH-ID.h	\
	EARFCN-Extended.h	\
	E-DCH-MAC-d-Flow-ID.h	\
	ENB-ID.h	\
	EncryptionAlgorithm.h	\
	EncryptionInformation.h	\
	EncryptionKey.h	\
	End-Of-CSFB.h	\
	EquipmentsToBeTraced.h	\
	E-UTRAN-Service-Handover.h	\
	Event.h	\
	Event1F-Parameters.h	\
	Event1I-Parameters.h	\
	ExtendedGuaranteedBitrate.h	\
	ExtendedMaxBitrate.h	\
	ExtendedRNC-ID.h	\
	FrameSequenceNumber.h	\
	FrequenceLayerConvergenceFlag.h	\
	GANSS-PositioningDataSet.h	\
	GANSS-PositioningMethodAndUsage.h	\
	GeographicalArea.h	\
	GeographicalCoordinates.h	\
	GA-AltitudeAndDirection.h	\
	GA-EllipsoidArc.h	\
	GA-Point.h	\
	GA-PointWithAltitude.h	\
	GA-PointWithAltitudeAndUncertaintyEllipsoid.h	\
	GA-PointWithUnCertainty.h	\
	GA-PointWithUnCertaintyEllipse.h	\
	GA-Polygon.h	\
	GA-UncertaintyEllipse.h	\
	GERAN-BSC-Container.h	\
	GERAN-Cell-ID.h	\
	GERAN-Classmark.h	\
	GlobalCN-ID.h	\
	GlobalRNC-ID.h	\
	GTP-TEI.h	\
	GuaranteedBitrate.h	\
	HigherBitratesThan16MbpsFlag.h	\
	HS-DSCH-MAC-d-Flow-ID.h	\
	IMEI.h	\
	IMEIGroup.h	\
	IMEIList.h	\
	IMEISV.h	\
	IMEISVGroup.h	\
	IMEISVList.h	\
	ImmediateMDT.h	\
	IMSI.h	\
	IncludeVelocity.h	\
	InformationExchangeID.h	\
	InformationExchangeType.h	\
	InformationRequested.h	\
	InformationRequestType.h	\
	InformationTransferID.h	\
	InformationTransferType.h	\
	IntegrityProtectionAlgorithm.h	\
	IntegrityProtectionInformation.h	\
	IntegrityProtectionKey.h	\
	InterSystemInformationTransferType.h	\
	InterSystemInformation-TransparentContainer.h	\
	IPMulticastAddress.h	\
	IuSignallingConnectionIdentifier.h	\
	IuTransportAssociation.h	\
	KeyStatus.h	\
	LA-LIST.h	\
	LAC.h	\
	LAI.h	\
	LastKnownServiceArea.h	\
	LastVisitedUTRANCell-Item.h	\
	LHN-ID.h	\
	Links-to-log.h	\
	ListOF-SNAs.h	\
	ListOfInterfacesToTrace.h	\
	InterfacesToTraceItem.h	\
	LoadValue.h	\
	LocationRelatedDataRequestType.h	\
	LocationRelatedDataRequestTypeSpecificToGERANIuMode.h	\
	LocationReportingTransferInformation.h	\
	ReportChangeOfSAI.h	\
	PeriodicReportingIndicator.h	\
	DirectReportingIndicator.h	\
	L3-Information.h	\
	M1Report.h	\
	M2Report.h	\
	M4Report.h	\
	M4-Collection-Parameters.h	\
	M4-Period.h	\
	M4-Threshold.h	\
	M5Report.h	\
	M5-Period.h	\
	M6Report.h	\
	M6-Period.h	\
	M7Report.h	\
	M7-Period.h	\
	Management-Based-MDT-Allowed.h	\
	MaxBitrate.h	\
	MaxSDU-Size.h	\
	MBMS-PTP-RAB-ID.h	\
	MBMSBearerServiceType.h	\
	MBMSCNDe-Registration.h	\
	MBMSCountingInformation.h	\
	MBMSHCIndicator.h	\
	MBMSIPMulticastAddressandAPNRequest.h	\
	MBMSLinkingInformation.h	\
	MBMSRegistrationRequestType.h	\
	MBMSServiceArea.h	\
	MBMSSessionDuration.h	\
	MBMSSessionIdentity.h	\
	MBMSSessionRepetitionNumber.h	\
	MDT-Activation.h	\
	MDTAreaScope.h	\
	MDT-Configuration.h	\
	MDTMode.h	\
	MDT-PLMN-List.h	\
	MDT-Report-Parameters.h	\
	MeasurementQuantity.h	\
	MeasurementsToActivate.h	\
	MSISDN.h	\
	NAS-PDU.h	\
	NAS-SequenceNumber.h	\
	NAS-SynchronisationIndicator.h	\
	NewBSS-To-OldBSS-Information.h	\
	NonSearchingIndication.h	\
	NRTLoadInformationValue.h	\
	Null-NRI.h	\
	NumberOfIuInstances.h	\
	NumberOfSteps.h	\
	Offload-RAB-Parameters.h	\
	Offload-RAB-Parameters-APN.h	\
	Offload-RAB-Parameters-ChargingCharacteristics.h	\
	OldBSS-ToNewBSS-Information.h	\
	OMC-ID.h	\
	Out-Of-UTRAN.h	\
	PagingAreaID.h	\
	PagingCause.h	\
	PDP-TypeInformation.h	\
	PDP-Type.h	\
	PDP-TypeInformation-extension.h	\
	PDP-Type-extension.h	\
	PDUType14FrameSequenceNumber.h	\
	PeriodicLocationInfo.h	\
	PermanentNAS-UE-ID.h	\
	PermittedEncryptionAlgorithms.h	\
	PermittedIntegrityProtectionAlgorithms.h	\
	LABased.h	\
	LAI-List.h	\
	LoggedMDT.h	\
	LoggingInterval.h	\
	LoggingDuration.h	\
	PLMNBased.h	\
	PLMNList.h	\
	PLMNidentity.h	\
	PLMNs-in-shared-network.h	\
	Port-Number.h	\
	PositioningDataDiscriminator.h	\
	PositioningDataSet.h	\
	PositioningMethodAndUsage.h	\
	PositioningPriority.h	\
	PositionData.h	\
	PositionDataSpecificToGERANIuMode.h	\
	Pre-emptionCapability.h	\
	Pre-emptionVulnerability.h	\
	PriorityLevel.h	\
	Priority-Class-Indicator.h	\
	ProvidedData.h	\
	PowerSavingIndicator.h	\
	P-TMSI.h	\
	QueuingAllowed.h	\
	RAB-AsymmetryIndicator.h	\
	RABased.h	\
	RAI-List.h	\
	RABDataVolumeReport.h	\
	RAB-ID.h	\
	RAB-Parameter-ExtendedGuaranteedBitrateList.h	\
	RAB-Parameter-ExtendedMaxBitrateList.h	\
	RAB-Parameter-GuaranteedBitrateList.h	\
	RAB-Parameter-MaxBitrateList.h	\
	RAB-Parameters.h	\
	RABParametersList.h	\
	RAB-SubflowCombinationBitRate.h	\
	RAB-TrCH-Mapping.h	\
	RAB-TrCH-MappingItem.h	\
	RAC.h	\
	RAI.h	\
	RAListofIdleModeUEs.h	\
	NotEmptyRAListofIdleModeUEs.h	\
	RAofIdleModeUEs.h	\
	LAListofIdleModeUEs.h	\
	RAT-Type.h	\
	RateControlAllowed.h	\
	RedirectAttemptFlag.h	\
	RedirectionCompleted.h	\
	RejectCauseValue.h	\
	RelocationRequirement.h	\
	RelocationType.h	\
	RepetitionNumber0.h	\
	RepetitionNumber1.h	\
	ReportArea.h	\
	ReportInterval.h	\
	ReportAmount.h	\
	RequestedGPSAssistanceData.h	\
	RequestedGANSSAssistanceData.h	\
	RequestedLocationRelatedDataType.h	\
	RequestedMBMSIPMulticastAddressandAPNRequest.h	\
	MBMSIPMulticastAddressandAPNlist.h	\
	RequestedMulticastServiceList.h	\
	Requested-RAB-Parameter-Values.h	\
	Requested-RAB-Parameter-ExtendedMaxBitrateList.h	\
	Requested-RAB-Parameter-ExtendedGuaranteedBitrateList.h	\
	Requested-RAB-Parameter-MaxBitrateList.h	\
	Requested-RAB-Parameter-GuaranteedBitrateList.h	\
	RequestType.h	\
	ResidualBitErrorRatio.h	\
	ResponseTime.h	\
	RIMInformation.h	\
	RIM-Transfer.h	\
	RIMRoutingAddress.h	\
	RNC-ID.h	\
	RNCTraceInformation.h	\
	RNSAPRelocationParameters.h	\
	RRC-Container.h	\
	RTLoadValue.h	\
	RSRVCC-HO-Indication.h	\
	RSRVCC-Information.h	\
	RSRVCC-Operation-Possible.h	\
	SAC.h	\
	SAI.h	\
	SAPI.h	\
	SessionUpdateID.h	\
	Shared-Network-Information.h	\
	Session-Re-establishment-Indicator.h	\
	SignallingIndication.h	\
	SDU-ErrorRatio.h	\
	SDU-FormatInformationParameters.h	\
	SDU-Parameters.h	\
	SGSN-Group-Identity.h	\
	SGSN-Group-ID.h	\
	SNA-Access-Information.h	\
	SNAC.h	\
	Service-Handover.h	\
	Source-ToTarget-TransparentContainer.h	\
	SourceeNodeB-ToTargeteNodeB-TransparentContainer.h	\
	SourceCellID.h	\
	SourceBSS-ToTargetBSS-TransparentContainer.h	\
	SourceID.h	\
	SourceRNC-ID.h	\
	SourceRNC-ToTargetRNC-TransparentContainer.h	\
	IRAT-Measurement-Configuration.h	\
	IRATmeasurementParameters.h	\
	RSRQ-Type.h	\
	RSRQ-Extension.h	\
	EUTRANFrequencies.h	\
	MeasBand.h	\
	SubscriberProfileIDforRFP.h	\
	SourceStatisticsDescriptor.h	\
	SupportedRAB-ParameterBitrateList.h	\
	SupportedBitrate.h	\
	SourceUTRANCellID.h	\
	SRB-ID.h	\
	SRB-TrCH-Mapping.h	\
	SRB-TrCH-MappingItem.h	\
	SRVCC-HO-Indication.h	\
	SRVCC-Information.h	\
	SRVCC-Operation-Possible.h	\
	SubflowSDU-Size.h	\
	TAC.h	\
	TAI.h	\
	Target-ToSource-TransparentContainer.h	\
	TargeteNodeB-ToSourceeNodeB-TransparentContainer.h	\
	TargetBSS-ToSourceBSS-TransparentContainer.h	\
	TargetCellId.h	\
	TargetID.h	\
	TargetENB-ID.h	\
	TargetRNC-ID.h	\
	TargetRNC-ToSourceRNC-TransparentContainer.h	\
	TBCD-STRING.h	\
	TemporaryUE-ID.h	\
	Time-UE-StayedInCell.h	\
	Time-UE-StayedInCell-EnhancedGranularity.h	\
	TimeToMBMSDataTransfer.h	\
	TimingDifferenceULDL.h	\
	TMGI.h	\
	TMSI.h	\
	TraceDepth.h	\
	TraceInformation.h	\
	TracePropagationParameters.h	\
	TraceRecordingSessionInformation.h	\
	TraceRecordingSessionReference.h	\
	TraceReference.h	\
	TraceType.h	\
	TrafficClass.h	\
	TrafficHandlingPriority.h	\
	TransferDelay.h	\
	UnsuccessfullyTransmittedDataVolume.h	\
	TransportLayerAddress.h	\
	TrCH-ID.h	\
	TrCH-ID-List.h	\
	TriggerID.h	\
	TunnelInformation.h	\
	TypeOfError.h	\
	UE-AggregateMaximumBitRate.h	\
	UE-AggregateMaximumBitRateDownlink.h	\
	UE-AggregateMaximumBitRateUplink.h	\
	UE-History-Information.h	\
	UE-ID.h	\
	UE-IsNotServed.h	\
	UE-IsServed.h	\
	UE-Usage-Type.h	\
	UERegistrationQueryResult.h	\
	UESBI-Iu.h	\
	UESBI-IuA.h	\
	UESBI-IuB.h	\
	UL-GTP-PDU-SequenceNumber.h	\
	UL-N-PDU-SequenceNumber.h	\
	UPInformation.h	\
	UPInitialisationFrame.h	\
	UP-ModeVersions.h	\
	USCH-ID.h	\
	UserPlaneMode.h	\
	UTRAN-CellID.h	\
	VelocityEstimate.h	\
	HorizontalVelocity.h	\
	HorizontalWithVerticalVelocity.h	\
	HorizontalVelocityWithUncertainty.h	\
	HorizontalWithVerticalVelocityAndUncertainty.h	\
	HorizontalSpeedAndBearing.h	\
	VerticalVelocity.h	\
	VerticalSpeedDirection.h	\
	VerticalAccuracyCode.h	\
	VoiceSupportMatchIndicator.h	\
	Criticality.h	\
	Presence.h	\
	PrivateIE-ID.h	\
	ProcedureCode.h	\
	ProtocolExtensionID.h	\
	ProtocolIE-ID.h	\
	TriggeringMessage.h	\
	ProtocolIE-Container.h	\
	ProtocolIE-Field.h	\
	ProtocolIE-ContainerPair.h	\
	ProtocolIE-FieldPair.h	\
	ProtocolIE-ContainerList.h	\
	ProtocolIE-ContainerPairList.h	\
	ProtocolExtensionContainer.h	\
	ProtocolExtensionField.h	\
	PrivateIE-Container.h	\
	PrivateIE-Field.h	\
	EXTERNAL.h

ASN_MODULE_HEADERS+=ANY.h
ASN_MODULE_SOURCES+=ANY.c
ASN_MODULE_HEADERS+=BOOLEAN.h
ASN_MODULE_SOURCES+=BOOLEAN.c
ASN_MODULE_HEADERS+=INTEGER.h
ASN_MODULE_HEADERS+=NativeEnumerated.h
ASN_MODULE_HEADERS+=GraphicString.h
ASN_MODULE_SOURCES+=GraphicString.c
ASN_MODULE_SOURCES+=INTEGER.c
ASN_MODULE_HEADERS+=NULL.h
ASN_MODULE_SOURCES+=NULL.c
ASN_MODULE_SOURCES+=NativeEnumerated.c
ASN_MODULE_HEADERS+=NativeInteger.h
ASN_MODULE_SOURCES+=NativeInteger.c
ASN_MODULE_HEADERS+=OBJECT_IDENTIFIER.h
ASN_MODULE_SOURCES+=OBJECT_IDENTIFIER.c
ASN_MODULE_HEADERS+=ObjectDescriptor.h
ASN_MODULE_SOURCES+=ObjectDescriptor.c
ASN_MODULE_HEADERS+=asn_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=asn_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=asn_SET_OF.h
ASN_MODULE_SOURCES+=asn_SET_OF.c
ASN_MODULE_HEADERS+=constr_CHOICE.h
ASN_MODULE_SOURCES+=constr_CHOICE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE.h
ASN_MODULE_SOURCES+=constr_SEQUENCE.c
ASN_MODULE_HEADERS+=constr_SEQUENCE_OF.h
ASN_MODULE_SOURCES+=constr_SEQUENCE_OF.c
ASN_MODULE_HEADERS+=constr_SET_OF.h
ASN_MODULE_SOURCES+=constr_SET_OF.c
ASN_MODULE_HEADERS+=asn_application.h
ASN_MODULE_HEADERS+=asn_system.h
ASN_MODULE_HEADERS+=asn_codecs.h
ASN_MODULE_HEADERS+=asn_internal.h
ASN_MODULE_HEADERS+=OCTET_STRING.h
ASN_MODULE_SOURCES+=OCTET_STRING.c
ASN_MODULE_HEADERS+=BIT_STRING.h
ASN_MODULE_SOURCES+=BIT_STRING.c
ASN_MODULE_SOURCES+=asn_codecs_prim.c
ASN_MODULE_HEADERS+=asn_codecs_prim.h
ASN_MODULE_HEADERS+=ber_tlv_length.h
ASN_MODULE_SOURCES+=ber_tlv_length.c
ASN_MODULE_HEADERS+=ber_tlv_tag.h
ASN_MODULE_SOURCES+=ber_tlv_tag.c
ASN_MODULE_HEADERS+=ber_decoder.h
ASN_MODULE_SOURCES+=ber_decoder.c
ASN_MODULE_HEADERS+=der_encoder.h
ASN_MODULE_SOURCES+=der_encoder.c
ASN_MODULE_HEADERS+=constr_TYPE.h
ASN_MODULE_SOURCES+=constr_TYPE.c
ASN_MODULE_HEADERS+=constraints.h
ASN_MODULE_SOURCES+=constraints.c
ASN_MODULE_HEADERS+=xer_support.h
ASN_MODULE_SOURCES+=xer_support.c
ASN_MODULE_HEADERS+=xer_decoder.h
ASN_MODULE_SOURCES+=xer_decoder.c
ASN_MODULE_HEADERS+=xer_encoder.h
ASN_MODULE_SOURCES+=xer_encoder.c
ASN_MODULE_HEADERS+=per_support.h
ASN_MODULE_SOURCES+=per_support.c
ASN_MODULE_HEADERS+=per_decoder.h
ASN_MODULE_SOURCES+=per_decoder.c
ASN_MODULE_HEADERS+=per_encoder.h
ASN_MODULE_SOURCES+=per_encoder.c
ASN_MODULE_HEADERS+=per_opentype.h
ASN_MODULE_SOURCES+=per_opentype.c
ASN_CONVERTER_SOURCES+=converter-sample.c
ASN_CONVERTER_SOURCES+=pdu_collection.c


lib_LTLIBRARIES=libsomething.la
libsomething_la_SOURCES=$(ASN_MODULE_SOURCES) $(ASN_MODULE_HEADERS)

# This file may be used as an input for make(3)
# Remove the lines below to convert it into a pure .am file
TARGET = ranap-dump
CFLAGS += -DJUNKTEST  -DPDU=RANAP_PDU -DASN_PDU_COLLECTION -I.
OBJS=${ASN_MODULE_SOURCES:.c=.o} ${ASN_CONVERTER_SOURCES:.c=.o}

all: RANAP-PDU.c $(TARGET)

$(TARGET): ${OBJS}
	$(CC) $(CFLAGS) -o $(TARGET) ${OBJS} $(LDFLAGS) $(LIBS)

.SUFFIXES:
.SUFFIXES: .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	rm -f $(TARGET)
	rm -f $(OBJS)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	../../asn1c/asn1c -S ../../skeletons -pdu=RANAP-PDU -pdu=auto -fcompound-names -gen-PER ../ranap-14.0.0.asn1


RANAP-PDU.c: ../sample.makefile.regen ../ranap-14.0.0.asn1
	make regen-makefile
	@touch RANAP-PDU.c
	make

regen-makefile:
	ASN1CMDOPTS="-pdu=auto -fcompound-names -gen-PER" \
	ASN1MODULES="../ranap-14.0.0.asn1" \
	ASN1PDU=RANAP-PDU \
	PROGNAME=ranap-dump \
	CFLAGS="" \
	../sample.makefile.regen

check: ${TARGET} check-ber check-xer check-per
	@echo ================
	@echo All tests passed
	@echo ================

check-ber:
	@if test -f sample-RANAP-PDU-1.[db]er ; then \
	for f in sample-RANAP-PDU-*.[db]er; do \
	for b in 1 17 33 980 8192; do \
	echo "Recoding $$f into XER and back ($$b)..."; \
	./${TARGET} -b $$b -iber -oxer $$f > ./.tmp.1.$$$$ || exit 2; \
	./${TARGET} -b $$b -ixer -oxer ./.tmp.1.$$$$ > ./.tmp.2.$$$$ || exit 3; \
	diff ./.tmp.1.$$$$ ./.tmp.2.$$$$ || exit 4; \
	rm -f ./.tmp.[12].$$$$; \
	echo "Test junking $$f (please wait)..."; \
	./${TARGET} -J0.0001 -n 1000 -b $$b -iber -onull $$f || exit 5; \
	./${TARGET} -J0.001 -n 1000 -b $$b -iber -onull $$f || exit 6; \
	done; done; fi

check-xer:
	@if test -f sample-RANAP-PDU-1.xer ; then \
	for f in sample-RANAP-PDU-*.xer; do \
	for b in 1 17 33 980 8192; do \
	echo "Recoding $$f into DER and back ($$b)..."; \
	./${TARGET} -b $$b -ixer -oder $$f > ./.tmp.1.$$$$ || exit 2; \
	./${TARGET} -b $$b -iber -oxer ./.tmp.1.$$$$ > ./.tmp.2.$$$$ || exit 3; \
	diff $$f ./.tmp.2.$$$$ || exit 4; \
	rm -f ./.tmp.[12].$$$$; \
	echo "Test junking $$f (please wait)..."; \
	./${TARGET} -J0.0001 -n 1000 -b $$b -ixer -onull $$f || exit 5; \
	./${TARGET} -J0.001 -n 1000 -b $$b -ixer -onull $$f || exit 6; \
	done; done; fi

check-per:
	@if test -f sample-RANAP-PDU-1-nopad.per ; then \
	for f in sample-RANAP-PDU-[1-9]-nopad.per; do \
	for b in 1 17 33 980 8192; do \
	echo "Recoding non-padded $$f into DER into XER and back ($$b)..."; \
	./${TARGET} -b $$b -per-nopad -iper -oder $$f > ./.tmp.1.$$$$ || exit 2; \
	./${TARGET} -b $$b -iber -oxer ./.tmp.1.$$$$ > ./.tmp.2.$$$$ || exit 3; \
	./${TARGET} -b $$b -ixer -oder ./.tmp.2.$$$$ > ./.tmp.3.$$$$ || exit 4; \
	diff ./.tmp.1.$$$$ ./.tmp.3.$$$$ || exit 5; \
	rm -f ./.tmp.[123].$$$$; \
	echo "Test junking $$f (please wait)..."; \
	./${TARGET} -J0.0001 -n 1000 -b $$b -per-nopad -iper -onull $$f || exit 6; \
	./${TARGET} -J0.001 -n 1000 -b $$b -per-nopad -iper -onull $$f || exit 7; \
	done; done; fi
	@if test -f sample-RANAP-PDU-1.per ; then \
	for f in sample-*-[1-9].per; do \
	pdu=`echo $$f | sed -E -e "s/sample-([A-Za-z-]+)-[0-9].*/\1/"`; \
	for b in 1 17 33 980 8192; do \
	echo "Recoding $$f into DER into XER and back ($$b)..."; \
	./${TARGET} -b $$b -p $$pdu -iper -oder $$f > ./.tmp.1.$$$$ || exit 3; \
	./${TARGET} -b $$b -p $$pdu -iber -oxer ./.tmp.1.$$$$ > ./.tmp.2.$$$$ || exit 4; \
	./${TARGET} -b $$b -p $$pdu -ixer -oper ./.tmp.2.$$$$ > ./.tmp.1.$$$$ || exit 5; \
	diff $$f ./.tmp.1.$$$$ || exit 6; \
	rm -f ./.tmp.[12].$$$$; \
	echo "Test junking $$f (please wait)..."; \
	./${TARGET} -J0.0001 -n 1000 -b $$b -iper -onull $$f || exit 7; \
	./${TARGET} -J0.001 -n 1000 -b $$b -iper -onull $$f || exit 8; \
	done; done; fi

distclean: clean
	rm -f $(ASN_MODULE_SOURCES)
	rm -f $(ASN_MODULE_HEADERS)
	rm -f $(ASN_CONVERTER_SOURCES) $(ASN_CONVERTER_HEADERS)
	rm -f Makefile.am.sample
